/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_ulcs.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "ACSE-apdu.h"

static asn_per_constraints_t asn_PER_type_ACSE_apdu_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ACSE_apdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ACSE_apdu, choice.aarq),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_AARQ_apdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aarq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACSE_apdu, choice.aare),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_AARE_apdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aare"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACSE_apdu, choice.rlrq),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		0,
		&asn_DEF_RLRQ_apdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlrq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACSE_apdu, choice.rlre),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_RLRE_apdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlre"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACSE_apdu, choice.abrt),
		(ASN_TAG_CLASS_APPLICATION | (4 << 2)),
		0,
		&asn_DEF_ABRT_apdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"abrt"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ACSE_apdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 }, /* aarq */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* aare */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 2, 0, 0 }, /* rlrq */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 3, 0, 0 }, /* rlre */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 4, 0, 0 } /* abrt */
};
static asn_CHOICE_specifics_t asn_SPC_ACSE_apdu_specs_1 = {
	sizeof(struct ACSE_apdu),
	offsetof(struct ACSE_apdu, _asn_ctx),
	offsetof(struct ACSE_apdu, present),
	sizeof(((struct ACSE_apdu *)0)->present),
	asn_MAP_ACSE_apdu_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ACSE_apdu = {
	"ACSE-apdu",
	"ACSE-apdu",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_ACSE_apdu_constr_1,
	asn_MBR_ACSE_apdu_1,
	5,	/* Elements count */
	&asn_SPC_ACSE_apdu_specs_1	/* Additional specs */
};

