/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMADSCAPDUVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_pmadsc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ADSAircraftPDU_H_
#define	_ADSAircraftPDU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Report.h"
#include "Reject.h"
#include "NonCompliance.h"
#include "PositiveAcknowledgement.h"
#include "RequestType.h"
#include "CancelRejectReason.h"
#include "ProviderAbortReason.h"
#include "UserAbortReason.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ADSAircraftPDU_PR {
	ADSAircraftPDU_PR_NOTHING,	/* No components present */
	ADSAircraftPDU_PR_aDS_report_PDU,
	ADSAircraftPDU_PR_aDS_accepted_PDU,
	ADSAircraftPDU_PR_aDS_rejected_PDU,
	ADSAircraftPDU_PR_aDS_ncn_PDU,
	ADSAircraftPDU_PR_aDS_positive_acknowledgement_PDU,
	ADSAircraftPDU_PR_aDS_cancel_positive_acknowledgement_PDU,
	ADSAircraftPDU_PR_aDS_cancel_negative_acknowledgement_PDU,
	ADSAircraftPDU_PR_aDS_provider_abort_PDU,
	ADSAircraftPDU_PR_aDS_user_abort_PDU,
	/* Extensions may appear below */
	
} ADSAircraftPDU_PR;

/* ADSAircraftPDU */
typedef struct ADSAircraftPDU {
	ADSAircraftPDU_PR present;
	union ADSAircraftPDU_u {
		Report_t	 aDS_report_PDU;
		Report_t	 aDS_accepted_PDU;
		Reject_t	 aDS_rejected_PDU;
		NonCompliance_t	 aDS_ncn_PDU;
		PositiveAcknowledgement_t	 aDS_positive_acknowledgement_PDU;
		RequestType_t	 aDS_cancel_positive_acknowledgement_PDU;
		CancelRejectReason_t	 aDS_cancel_negative_acknowledgement_PDU;
		ProviderAbortReason_t	 aDS_provider_abort_PDU;
		UserAbortReason_t	 aDS_user_abort_PDU;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ADSAircraftPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ADSAircraftPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _ADSAircraftPDU_H_ */
#include "asn_internal.h"
