/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMADSCAPDUVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_pmadsc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "ADSGroundPDU.h"

static asn_per_constraints_t asn_PER_type_ADSGroundPDU_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ADSGroundPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ADSGroundPDU, choice.aDS_cancel_all_contracts_PDU),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CancelAllContracts,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aDS-cancel-all-contracts-PDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ADSGroundPDU, choice.aDS_cancel_contract_PDU),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CancelContract,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aDS-cancel-contract-PDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ADSGroundPDU, choice.aDS_contract_PDU),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ContractRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aDS-contract-PDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ADSGroundPDU, choice.aDS_provider_abort_PDU),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProviderAbortReason,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aDS-provider-abort-PDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ADSGroundPDU, choice.aDS_user_abort_PDU),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UserAbortReason,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aDS-user-abort-PDU"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ADSGroundPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aDS-cancel-all-contracts-PDU */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aDS-cancel-contract-PDU */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aDS-contract-PDU */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* aDS-provider-abort-PDU */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* aDS-user-abort-PDU */
};
static asn_CHOICE_specifics_t asn_SPC_ADSGroundPDU_specs_1 = {
	sizeof(struct ADSGroundPDU),
	offsetof(struct ADSGroundPDU, _asn_ctx),
	offsetof(struct ADSGroundPDU, present),
	sizeof(((struct ADSGroundPDU *)0)->present),
	asn_MAP_ADSGroundPDU_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ADSGroundPDU = {
	"ADSGroundPDU",
	"ADSGroundPDU",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_ADSGroundPDU_constr_1,
	asn_MBR_ADSGroundPDU_1,
	5,	/* Elements count */
	&asn_SPC_ADSGroundPDU_specs_1	/* Additional specs */
};

