/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMADSCAPDUVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_pmadsc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ADSMessage_H_
#define	_ADSMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ADSMessage */
typedef BIT_STRING_t	 ADSMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ADSMessage;
asn_struct_free_f ADSMessage_free;
asn_struct_print_f ADSMessage_print;
asn_constr_check_f ADSMessage_constraint;
ber_type_decoder_f ADSMessage_decode_ber;
der_type_encoder_f ADSMessage_encode_der;
xer_type_decoder_f ADSMessage_decode_xer;
xer_type_encoder_f ADSMessage_encode_xer;
per_type_decoder_f ADSMessage_decode_uper;
per_type_encoder_f ADSMessage_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ADSMessage_H_ */
#include "asn_internal.h"
