/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ADSNonCompliance_H_
#define	_ADSNonCompliance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ContractNumber.h"
#include "ConnectedATSUList.h"
#include "ADSEmergencyUrgencyStatus.h"
#include "EPPLimitations.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ContractDetailsNotSupporting;

/* ADSNonCompliance */
typedef struct ADSNonCompliance {
	ContractNumber_t	 contractNumber;
	ConnectedATSUList_t	 connectedATSUList;
	ADSEmergencyUrgencyStatus_t	*emergencyUrgency	/* OPTIONAL */;
	EPPLimitations_t	*eppLimitations	/* OPTIONAL */;
	struct ContractDetailsNotSupporting	*contractDetailsNotSupporting	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ADSNonCompliance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ADSNonCompliance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ContractDetailsNotSupporting.h"

#endif	/* _ADSNonCompliance_H_ */
#include "asn_internal.h"
