/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ADSPositiveAcknowledgement_H_
#define	_ADSPositiveAcknowledgement_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ContractNumber.h"
#include "ADSv2RequestType.h"
#include "ConnectedATSUList.h"
#include "ADSEmergencyUrgencyStatus.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ADSPositiveAcknowledgement */
typedef struct ADSPositiveAcknowledgement {
	ContractNumber_t	 contractNumber;
	ADSv2RequestType_t	 requestType;
	ConnectedATSUList_t	 connectedATSUList;
	ADSEmergencyUrgencyStatus_t	*emergencyUrgency	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ADSPositiveAcknowledgement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ADSPositiveAcknowledgement;

#ifdef __cplusplus
}
#endif

#endif	/* _ADSPositiveAcknowledgement_H_ */
#include "asn_internal.h"
