/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ADSReject_H_
#define	_ADSReject_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ContractNumber.h"
#include "ConnectedATSUList.h"
#include "ADSEmergencyUrgencyStatus.h"
#include "RejectDetails.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ADSReject */
typedef struct ADSReject {
	ContractNumber_t	*contractNumber	/* OPTIONAL */;
	ConnectedATSUList_t	 connectedATSUList;
	ADSEmergencyUrgencyStatus_t	*emergencyUrgency	/* OPTIONAL */;
	RejectDetails_t	 rejectDetails;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ADSReject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ADSReject;

#ifdef __cplusplus
}
#endif

#endif	/* _ADSReject_H_ */
#include "asn_internal.h"
