/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ADSReport_H_
#define	_ADSReport_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DemandReport.h"
#include "EventReport.h"
#include "PeriodicReport.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ADSReport_PR {
	ADSReport_PR_NOTHING,	/* No components present */
	ADSReport_PR_demand_report,
	ADSReport_PR_event_report,
	ADSReport_PR_periodic_report
} ADSReport_PR;

/* ADSReport */
typedef struct ADSReport {
	ADSReport_PR present;
	union ADSReport_u {
		DemandReport_t	 demand_report;
		EventReport_t	 event_report;
		PeriodicReport_t	 periodic_report;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ADSReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ADSReport;

#ifdef __cplusplus
}
#endif

#endif	/* _ADSReport_H_ */
#include "asn_internal.h"
