/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ADSv2WindSpeed_H_
#define	_ADSv2WindSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ADSv2WindSpeedKts.h"
#include "ADSv2WindSpeedKmh.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ADSv2WindSpeed_PR {
	ADSv2WindSpeed_PR_NOTHING,	/* No components present */
	ADSv2WindSpeed_PR_kt,
	ADSv2WindSpeed_PR_kmh
} ADSv2WindSpeed_PR;

/* ADSv2WindSpeed */
typedef struct ADSv2WindSpeed {
	ADSv2WindSpeed_PR present;
	union ADSv2WindSpeed_u {
		ADSv2WindSpeedKts_t	 kt;
		ADSv2WindSpeedKmh_t	 kmh;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ADSv2WindSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ADSv2WindSpeed;

#ifdef __cplusplus
}
#endif

#endif	/* _ADSv2WindSpeed_H_ */
#include "asn_internal.h"
