/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_AircraftTypeOTrafficLocationEtpO_H_
#define	_AircraftTypeOTrafficLocationEtpO_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AircraftType.h"
#include "TrafficLocation.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Time;

/* AircraftTypeOTrafficLocationEtpO */
typedef struct AircraftTypeOTrafficLocationEtpO {
	AircraftType_t	*aircraftType	/* OPTIONAL */;
	TrafficLocation_t	 trafficLocation;
	struct Time	*etp	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AircraftTypeOTrafficLocationEtpO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AircraftTypeOTrafficLocationEtpO;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Time.h"

#endif	/* _AircraftTypeOTrafficLocationEtpO_H_ */
#include "asn_internal.h"
