/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CMMessageSetVersion1"
 * 	found in "atn-cm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_AirportDestination_H_
#define	_AirportDestination_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Airport.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AirportDestination */
typedef Airport_t	 AirportDestination_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AirportDestination;
asn_struct_free_f AirportDestination_free;
asn_struct_print_f AirportDestination_print;
asn_constr_check_f AirportDestination_constraint;
ber_type_decoder_f AirportDestination_decode_ber;
der_type_encoder_f AirportDestination_encode_der;
xer_type_decoder_f AirportDestination_decode_xer;
xer_type_encoder_f AirportDestination_encode_xer;
per_type_decoder_f AirportDestination_decode_uper;
per_type_encoder_f AirportDestination_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AirportDestination_H_ */
#include "asn_internal.h"
