/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_Airspeed_H_
#define	_Airspeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SpeedMach.h"
#include "Ias.h"
#include "MachAndIas.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Airspeed_PR {
	Airspeed_PR_NOTHING,	/* No components present */
	Airspeed_PR_mach,
	Airspeed_PR_ias,
	Airspeed_PR_mach_and_ias
} Airspeed_PR;

/* Airspeed */
typedef struct Airspeed {
	Airspeed_PR present;
	union Airspeed_u {
		SpeedMach_t	 mach;
		Ias_t	 ias;
		MachAndIas_t	 mach_and_ias;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Airspeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Airspeed;

#ifdef __cplusplus
}
#endif

#endif	/* _Airspeed_H_ */
#include "asn_internal.h"
