/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "Airspeed.h"

static asn_per_constraints_t asn_PER_type_Airspeed_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Airspeed_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Airspeed, choice.mach),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SpeedMach,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mach"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Airspeed, choice.ias),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Ias,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ias"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Airspeed, choice.mach_and_ias),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MachAndIas,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mach-and-ias"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Airspeed_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mach */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ias */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* mach-and-ias */
};
static asn_CHOICE_specifics_t asn_SPC_Airspeed_specs_1 = {
	sizeof(struct Airspeed),
	offsetof(struct Airspeed, _asn_ctx),
	offsetof(struct Airspeed, present),
	sizeof(((struct Airspeed *)0)->present),
	asn_MAP_Airspeed_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Airspeed = {
	"Airspeed",
	"Airspeed",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Airspeed_constr_1,
	asn_MBR_Airspeed_1,
	3,	/* Elements count */
	&asn_SPC_Airspeed_specs_1	/* Additional specs */
};

