/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_AltimeterSetting_H_
#define	_AltimeterSetting_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Altimeter.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AltimeterSetting_PR {
	AltimeterSetting_PR_NOTHING,	/* No components present */
	AltimeterSetting_PR_qFE,
	AltimeterSetting_PR_qNH
} AltimeterSetting_PR;

/* AltimeterSetting */
typedef struct AltimeterSetting {
	AltimeterSetting_PR present;
	union AltimeterSetting_u {
		Altimeter_t	 qFE;
		Altimeter_t	 qNH;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AltimeterSetting_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AltimeterSetting;

#ifdef __cplusplus
}
#endif

#endif	/* _AltimeterSetting_H_ */
#include "asn_internal.h"
