/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_AltimeterMetric_H_
#define	_AltimeterMetric_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AltimeterMetric */
typedef long	 AltimeterMetric_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AltimeterMetric;
asn_struct_free_f AltimeterMetric_free;
asn_struct_print_f AltimeterMetric_print;
asn_constr_check_f AltimeterMetric_constraint;
ber_type_decoder_f AltimeterMetric_decode_ber;
der_type_encoder_f AltimeterMetric_encode_der;
xer_type_decoder_f AltimeterMetric_decode_xer;
xer_type_encoder_f AltimeterMetric_encode_xer;
per_type_decoder_f AltimeterMetric_decode_uper;
per_type_encoder_f AltimeterMetric_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AltimeterMetric_H_ */
#include "asn_internal.h"
