/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "atn-ulcs.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_AP_title_form1_H_
#define	_AP_title_form1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Name.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AP-title-form1 */
typedef Name_t	 AP_title_form1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AP_title_form1;
asn_struct_free_f AP_title_form1_free;
asn_struct_print_f AP_title_form1_print;
asn_constr_check_f AP_title_form1_constraint;
ber_type_decoder_f AP_title_form1_decode_ber;
der_type_encoder_f AP_title_form1_encode_der;
xer_type_decoder_f AP_title_form1_decode_xer;
xer_type_encoder_f AP_title_form1_encode_xer;
per_type_decoder_f AP_title_form1_decode_uper;
per_type_encoder_f AP_title_form1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AP_title_form1_H_ */
#include "asn_internal.h"
