/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_ATCDownlinkMessageData_H_
#define	_ATCDownlinkMessageData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ATCDownlinkMsgElementIdSequence.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RouteClearanceSequence;

/* ATCDownlinkMessageData */
typedef struct ATCDownlinkMessageData {
	ATCDownlinkMsgElementIdSequence_t	 elementIds;
	struct ATCDownlinkMessageData__constrainedData {
		struct RouteClearanceSequence	*routeClearanceData	/* OPTIONAL */;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *constrainedData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATCDownlinkMessageData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATCDownlinkMessageData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RouteClearanceSequence.h"

#endif	/* _ATCDownlinkMessageData_H_ */
#include <asn_internal.h>
