/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ATCDownlinkRouteClearanceConstrainedData_H_
#define	_ATCDownlinkRouteClearanceConstrainedData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RouteClearanceSequence;
struct RouteClearanceR;

/* ATCDownlinkRouteClearanceConstrainedData */
typedef struct ATCDownlinkRouteClearanceConstrainedData {
	struct RouteClearanceSequence	*routeClearanceData	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RouteClearanceR	*routeClearanceDataR	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATCDownlinkRouteClearanceConstrainedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATCDownlinkRouteClearanceConstrainedData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RouteClearanceSequence.h"
#include "RouteClearanceR.h"

#endif	/* _ATCDownlinkRouteClearanceConstrainedData_H_ */
#include "asn_internal.h"
