/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ATCUplinkMsgElementId_H_
#define	_ATCUplinkMsgElementId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "Level.h"
#include "Time.h"
#include "Position.h"
#include "TimeLevel.h"
#include "PositionLevel.h"
#include "LevelTime.h"
#include "LevelPosition.h"
#include "LevelLevel.h"
#include "PositionLevelLevel.h"
#include "PositionTime.h"
#include "PositionTimeTime.h"
#include "PositionSpeed.h"
#include "PositionTimeLevel.h"
#include "PositionLevelSpeed.h"
#include "TimePositionLevel.h"
#include "TimePositionLevelSpeed.h"
#include "DistanceSpecifiedDirection.h"
#include "PositionDistanceSpecifiedDirection.h"
#include "TimeDistanceSpecifiedDirection.h"
#include "DepartureClearance.h"
#include "TimePosition.h"
#include "PositionPosition.h"
#include "PositionRouteClearanceIndex.h"
#include "RouteClearanceIndex.h"
#include "ProcedureName.h"
#include "PositionProcedureName.h"
#include "HoldClearance.h"
#include "DirectionDegrees.h"
#include "PositionDegrees.h"
#include "TimeSpeed.h"
#include "LevelSpeed.h"
#include "TimeSpeedSpeed.h"
#include "PositionSpeedSpeed.h"
#include "LevelSpeedSpeed.h"
#include "Speed.h"
#include "SpeedSpeed.h"
#include "UnitNameFrequency.h"
#include "PositionUnitNameFrequency.h"
#include "TimeUnitNameFrequency.h"
#include "Code.h"
#include "SpeedTypeSpeedTypeSpeedType.h"
#include "Altimeter.h"
#include "Frequency.h"
#include "ATISCode.h"
#include "ErrorInformation.h"
#include "Facility.h"
#include "FacilityDesignation.h"
#include "TrafficType.h"
#include "FreeText.h"
#include "VerticalRate.h"
#include "ToFromPosition.h"
#include "TimeToFromPosition.h"
#include "Degrees.h"
#include "FacilityDesignationATISCode.h"
#include "FacilityDesignationAltimeter.h"
#include "RunwayRVR.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ATCUplinkMsgElementId_PR {
	ATCUplinkMsgElementId_PR_NOTHING,	/* No components present */
	ATCUplinkMsgElementId_PR_uM0NULL,
	ATCUplinkMsgElementId_PR_uM1NULL,
	ATCUplinkMsgElementId_PR_uM2NULL,
	ATCUplinkMsgElementId_PR_uM3NULL,
	ATCUplinkMsgElementId_PR_uM4NULL,
	ATCUplinkMsgElementId_PR_uM5NULL,
	ATCUplinkMsgElementId_PR_uM6Level,
	ATCUplinkMsgElementId_PR_uM7Time,
	ATCUplinkMsgElementId_PR_uM8Position,
	ATCUplinkMsgElementId_PR_uM9Time,
	ATCUplinkMsgElementId_PR_uM10Position,
	ATCUplinkMsgElementId_PR_uM11Time,
	ATCUplinkMsgElementId_PR_uM12Position,
	ATCUplinkMsgElementId_PR_uM13TimeLevel,
	ATCUplinkMsgElementId_PR_uM14PositionLevel,
	ATCUplinkMsgElementId_PR_uM15TimeLevel,
	ATCUplinkMsgElementId_PR_uM16PositionLevel,
	ATCUplinkMsgElementId_PR_uM17TimeLevel,
	ATCUplinkMsgElementId_PR_uM18PositionLevel,
	ATCUplinkMsgElementId_PR_uM19Level,
	ATCUplinkMsgElementId_PR_uM20Level,
	ATCUplinkMsgElementId_PR_uM21TimeLevel,
	ATCUplinkMsgElementId_PR_uM22PositionLevel,
	ATCUplinkMsgElementId_PR_uM23Level,
	ATCUplinkMsgElementId_PR_uM24TimeLevel,
	ATCUplinkMsgElementId_PR_uM25PositionLevel,
	ATCUplinkMsgElementId_PR_uM26LevelTime,
	ATCUplinkMsgElementId_PR_uM27LevelPosition,
	ATCUplinkMsgElementId_PR_uM28LevelTime,
	ATCUplinkMsgElementId_PR_uM29LevelPosition,
	ATCUplinkMsgElementId_PR_uM30LevelLevel,
	ATCUplinkMsgElementId_PR_uM31LevelLevel,
	ATCUplinkMsgElementId_PR_uM32LevelLevel,
	ATCUplinkMsgElementId_PR_uM33NULL,
	ATCUplinkMsgElementId_PR_uM34Level,
	ATCUplinkMsgElementId_PR_uM35Level,
	ATCUplinkMsgElementId_PR_uM36Level,
	ATCUplinkMsgElementId_PR_uM37Level,
	ATCUplinkMsgElementId_PR_uM38Level,
	ATCUplinkMsgElementId_PR_uM39Level,
	ATCUplinkMsgElementId_PR_uM40NULL,
	ATCUplinkMsgElementId_PR_uM41NULL,
	ATCUplinkMsgElementId_PR_uM42PositionLevel,
	ATCUplinkMsgElementId_PR_uM43PositionLevel,
	ATCUplinkMsgElementId_PR_uM44PositionLevel,
	ATCUplinkMsgElementId_PR_uM45PositionLevel,
	ATCUplinkMsgElementId_PR_uM46PositionLevel,
	ATCUplinkMsgElementId_PR_uM47PositionLevel,
	ATCUplinkMsgElementId_PR_uM48PositionLevel,
	ATCUplinkMsgElementId_PR_uM49PositionLevel,
	ATCUplinkMsgElementId_PR_uM50PositionLevelLevel,
	ATCUplinkMsgElementId_PR_uM51PositionTime,
	ATCUplinkMsgElementId_PR_uM52PositionTime,
	ATCUplinkMsgElementId_PR_uM53PositionTime,
	ATCUplinkMsgElementId_PR_uM54PositionTimeTime,
	ATCUplinkMsgElementId_PR_uM55PositionSpeed,
	ATCUplinkMsgElementId_PR_uM56PositionSpeed,
	ATCUplinkMsgElementId_PR_uM57PositionSpeed,
	ATCUplinkMsgElementId_PR_uM58PositionTimeLevel,
	ATCUplinkMsgElementId_PR_uM59PositionTimeLevel,
	ATCUplinkMsgElementId_PR_uM60PositionTimeLevel,
	ATCUplinkMsgElementId_PR_uM61PositionLevelSpeed,
	ATCUplinkMsgElementId_PR_uM62TimePositionLevel,
	ATCUplinkMsgElementId_PR_uM63TimePositionLevelSpeed,
	ATCUplinkMsgElementId_PR_uM64DistanceSpecifiedDirection,
	ATCUplinkMsgElementId_PR_uM65PositionDistanceSpecifiedDirection,
	ATCUplinkMsgElementId_PR_uM66TimeDistanceSpecifiedDirection,
	ATCUplinkMsgElementId_PR_uM67NULL,
	ATCUplinkMsgElementId_PR_uM68Position,
	ATCUplinkMsgElementId_PR_uM69Time,
	ATCUplinkMsgElementId_PR_uM70Position,
	ATCUplinkMsgElementId_PR_uM71Time,
	ATCUplinkMsgElementId_PR_uM72NULL,
	ATCUplinkMsgElementId_PR_uM73DepartureClearance,
	ATCUplinkMsgElementId_PR_uM74Position,
	ATCUplinkMsgElementId_PR_uM75Position,
	ATCUplinkMsgElementId_PR_uM76TimePosition,
	ATCUplinkMsgElementId_PR_uM77PositionPosition,
	ATCUplinkMsgElementId_PR_uM78LevelPosition,
	ATCUplinkMsgElementId_PR_uM79PositionRouteClearance,
	ATCUplinkMsgElementId_PR_uM80RouteClearance,
	ATCUplinkMsgElementId_PR_uM81ProcedureName,
	ATCUplinkMsgElementId_PR_uM82DistanceSpecifiedDirection,
	ATCUplinkMsgElementId_PR_uM83PositionRouteClearance,
	ATCUplinkMsgElementId_PR_uM84PositionProcedureName,
	ATCUplinkMsgElementId_PR_uM85RouteClearance,
	ATCUplinkMsgElementId_PR_uM86PositionRouteClearance,
	ATCUplinkMsgElementId_PR_uM87Position,
	ATCUplinkMsgElementId_PR_uM88PositionPosition,
	ATCUplinkMsgElementId_PR_uM89TimePosition,
	ATCUplinkMsgElementId_PR_uM90LevelPosition,
	ATCUplinkMsgElementId_PR_uM91HoldClearance,
	ATCUplinkMsgElementId_PR_uM92PositionLevel,
	ATCUplinkMsgElementId_PR_uM93Time,
	ATCUplinkMsgElementId_PR_uM94DirectionDegrees,
	ATCUplinkMsgElementId_PR_uM95DirectionDegrees,
	ATCUplinkMsgElementId_PR_uM96NULL,
	ATCUplinkMsgElementId_PR_uM97PositionDegrees,
	ATCUplinkMsgElementId_PR_uM98DirectionDegrees,
	ATCUplinkMsgElementId_PR_uM99ProcedureName,
	ATCUplinkMsgElementId_PR_uM100TimeSpeed,
	ATCUplinkMsgElementId_PR_uM101PositionSpeed,
	ATCUplinkMsgElementId_PR_uM102LevelSpeed,
	ATCUplinkMsgElementId_PR_uM103TimeSpeedSpeed,
	ATCUplinkMsgElementId_PR_uM104PositionSpeedSpeed,
	ATCUplinkMsgElementId_PR_uM105LevelSpeedSpeed,
	ATCUplinkMsgElementId_PR_uM106Speed,
	ATCUplinkMsgElementId_PR_uM107NULL,
	ATCUplinkMsgElementId_PR_uM108Speed,
	ATCUplinkMsgElementId_PR_uM109Speed,
	ATCUplinkMsgElementId_PR_uM110SpeedSpeed,
	ATCUplinkMsgElementId_PR_uM111Speed,
	ATCUplinkMsgElementId_PR_uM112Speed,
	ATCUplinkMsgElementId_PR_uM113Speed,
	ATCUplinkMsgElementId_PR_uM114Speed,
	ATCUplinkMsgElementId_PR_uM115Speed,
	ATCUplinkMsgElementId_PR_uM116NULL,
	ATCUplinkMsgElementId_PR_uM117UnitNameFrequency,
	ATCUplinkMsgElementId_PR_uM118PositionUnitNameFrequency,
	ATCUplinkMsgElementId_PR_uM119TimeUnitNameFrequency,
	ATCUplinkMsgElementId_PR_uM120UnitNameFrequency,
	ATCUplinkMsgElementId_PR_uM121PositionUnitNameFrequency,
	ATCUplinkMsgElementId_PR_uM122TimeUnitNameFrequency,
	ATCUplinkMsgElementId_PR_uM123Code,
	ATCUplinkMsgElementId_PR_uM124NULL,
	ATCUplinkMsgElementId_PR_uM125NULL,
	ATCUplinkMsgElementId_PR_uM126NULL,
	ATCUplinkMsgElementId_PR_uM127NULL,
	ATCUplinkMsgElementId_PR_uM128Level,
	ATCUplinkMsgElementId_PR_uM129Level,
	ATCUplinkMsgElementId_PR_uM130Position,
	ATCUplinkMsgElementId_PR_uM131NULL,
	ATCUplinkMsgElementId_PR_uM132NULL,
	ATCUplinkMsgElementId_PR_uM133NULL,
	ATCUplinkMsgElementId_PR_uM134SpeedTypeSpeedTypeSpeedType,
	ATCUplinkMsgElementId_PR_uM135NULL,
	ATCUplinkMsgElementId_PR_uM136NULL,
	ATCUplinkMsgElementId_PR_uM137NULL,
	ATCUplinkMsgElementId_PR_uM138NULL,
	ATCUplinkMsgElementId_PR_uM139NULL,
	ATCUplinkMsgElementId_PR_uM140NULL,
	ATCUplinkMsgElementId_PR_uM141NULL,
	ATCUplinkMsgElementId_PR_uM142NULL,
	ATCUplinkMsgElementId_PR_uM143NULL,
	ATCUplinkMsgElementId_PR_uM144NULL,
	ATCUplinkMsgElementId_PR_uM145NULL,
	ATCUplinkMsgElementId_PR_uM146NULL,
	ATCUplinkMsgElementId_PR_uM147NULL,
	ATCUplinkMsgElementId_PR_uM148Level,
	ATCUplinkMsgElementId_PR_uM149LevelPosition,
	ATCUplinkMsgElementId_PR_uM150LevelTime,
	ATCUplinkMsgElementId_PR_uM151Speed,
	ATCUplinkMsgElementId_PR_uM152DistanceSpecifiedDirection,
	ATCUplinkMsgElementId_PR_uM153Altimeter,
	ATCUplinkMsgElementId_PR_uM154NULL,
	ATCUplinkMsgElementId_PR_uM155Position,
	ATCUplinkMsgElementId_PR_uM156NULL,
	ATCUplinkMsgElementId_PR_uM157Frequency,
	ATCUplinkMsgElementId_PR_uM158AtisCode,
	ATCUplinkMsgElementId_PR_uM159ErrorInformation,
	ATCUplinkMsgElementId_PR_uM160Facility,
	ATCUplinkMsgElementId_PR_uM161NULL,
	ATCUplinkMsgElementId_PR_uM162NULL,
	ATCUplinkMsgElementId_PR_uM163FacilityDesignation,
	ATCUplinkMsgElementId_PR_uM164NULL,
	ATCUplinkMsgElementId_PR_uM165NULL,
	ATCUplinkMsgElementId_PR_uM166TrafficType,
	ATCUplinkMsgElementId_PR_uM167NULL,
	ATCUplinkMsgElementId_PR_uM168NULL,
	ATCUplinkMsgElementId_PR_uM169FreeText,
	ATCUplinkMsgElementId_PR_uM170FreeText,
	ATCUplinkMsgElementId_PR_uM171VerticalRate,
	ATCUplinkMsgElementId_PR_uM172VerticalRate,
	ATCUplinkMsgElementId_PR_uM173VerticalRate,
	ATCUplinkMsgElementId_PR_uM174VerticalRate,
	ATCUplinkMsgElementId_PR_uM175Level,
	ATCUplinkMsgElementId_PR_uM176NULL,
	ATCUplinkMsgElementId_PR_uM177NULL,
	ATCUplinkMsgElementId_PR_uM178NULL,
	ATCUplinkMsgElementId_PR_uM179NULL,
	ATCUplinkMsgElementId_PR_uM180LevelLevel,
	ATCUplinkMsgElementId_PR_uM181ToFromPosition,
	ATCUplinkMsgElementId_PR_uM182NULL,
	ATCUplinkMsgElementId_PR_uM183FreeText,
	ATCUplinkMsgElementId_PR_uM184TimeToFromPosition,
	ATCUplinkMsgElementId_PR_uM185PositionLevel,
	ATCUplinkMsgElementId_PR_uM186PositionLevel,
	ATCUplinkMsgElementId_PR_uM187FreeText,
	ATCUplinkMsgElementId_PR_uM188PositionSpeed,
	ATCUplinkMsgElementId_PR_uM189Speed,
	ATCUplinkMsgElementId_PR_uM190Degrees,
	ATCUplinkMsgElementId_PR_uM191NULL,
	ATCUplinkMsgElementId_PR_uM192LevelTime,
	ATCUplinkMsgElementId_PR_uM193NULL,
	ATCUplinkMsgElementId_PR_uM194FreeText,
	ATCUplinkMsgElementId_PR_uM195FreeText,
	ATCUplinkMsgElementId_PR_uM196FreeText,
	ATCUplinkMsgElementId_PR_uM197FreeText,
	ATCUplinkMsgElementId_PR_uM198FreeText,
	ATCUplinkMsgElementId_PR_uM199FreeText,
	ATCUplinkMsgElementId_PR_uM200NULL,
	ATCUplinkMsgElementId_PR_uM201NULL,
	ATCUplinkMsgElementId_PR_uM202NULL,
	ATCUplinkMsgElementId_PR_uM203FreeText,
	ATCUplinkMsgElementId_PR_uM204FreeText,
	ATCUplinkMsgElementId_PR_uM205FreeText,
	ATCUplinkMsgElementId_PR_uM206FreeText,
	ATCUplinkMsgElementId_PR_uM207FreeText,
	ATCUplinkMsgElementId_PR_uM208FreeText,
	ATCUplinkMsgElementId_PR_uM209LevelPosition,
	ATCUplinkMsgElementId_PR_uM210Position,
	ATCUplinkMsgElementId_PR_uM211NULL,
	ATCUplinkMsgElementId_PR_uM212FacilityDesignationATISCode,
	ATCUplinkMsgElementId_PR_uM213FacilityDesignationAltimeter,
	ATCUplinkMsgElementId_PR_uM214RunwayRVR,
	ATCUplinkMsgElementId_PR_uM215DirectionDegrees,
	ATCUplinkMsgElementId_PR_uM216NULL,
	ATCUplinkMsgElementId_PR_uM217NULL,
	ATCUplinkMsgElementId_PR_uM218NULL,
	ATCUplinkMsgElementId_PR_uM219Level,
	ATCUplinkMsgElementId_PR_uM220Level,
	ATCUplinkMsgElementId_PR_uM221Degrees,
	ATCUplinkMsgElementId_PR_uM222NULL,
	ATCUplinkMsgElementId_PR_uM223NULL,
	ATCUplinkMsgElementId_PR_uM224NULL,
	ATCUplinkMsgElementId_PR_uM225NULL,
	ATCUplinkMsgElementId_PR_uM226Time,
	ATCUplinkMsgElementId_PR_uM227NULL,
	ATCUplinkMsgElementId_PR_uM228Position,
	ATCUplinkMsgElementId_PR_uM229NULL,
	ATCUplinkMsgElementId_PR_uM230NULL,
	ATCUplinkMsgElementId_PR_uM231NULL,
	ATCUplinkMsgElementId_PR_uM232NULL,
	ATCUplinkMsgElementId_PR_uM233NULL,
	ATCUplinkMsgElementId_PR_uM234NULL,
	ATCUplinkMsgElementId_PR_uM235NULL,
	ATCUplinkMsgElementId_PR_uM236NULL,
	ATCUplinkMsgElementId_PR_uM237NULL,
	/* Extensions may appear below */
	
} ATCUplinkMsgElementId_PR;

/* ATCUplinkMsgElementId */
typedef struct ATCUplinkMsgElementId {
	ATCUplinkMsgElementId_PR present;
	union ATCUplinkMsgElementId_u {
		NULL_t	 uM0NULL;
		NULL_t	 uM1NULL;
		NULL_t	 uM2NULL;
		NULL_t	 uM3NULL;
		NULL_t	 uM4NULL;
		NULL_t	 uM5NULL;
		Level_t	 uM6Level;
		Time_t	 uM7Time;
		Position_t	 uM8Position;
		Time_t	 uM9Time;
		Position_t	 uM10Position;
		Time_t	 uM11Time;
		Position_t	 uM12Position;
		TimeLevel_t	 uM13TimeLevel;
		PositionLevel_t	 uM14PositionLevel;
		TimeLevel_t	 uM15TimeLevel;
		PositionLevel_t	 uM16PositionLevel;
		TimeLevel_t	 uM17TimeLevel;
		PositionLevel_t	 uM18PositionLevel;
		Level_t	 uM19Level;
		Level_t	 uM20Level;
		TimeLevel_t	 uM21TimeLevel;
		PositionLevel_t	 uM22PositionLevel;
		Level_t	 uM23Level;
		TimeLevel_t	 uM24TimeLevel;
		PositionLevel_t	 uM25PositionLevel;
		LevelTime_t	 uM26LevelTime;
		LevelPosition_t	 uM27LevelPosition;
		LevelTime_t	 uM28LevelTime;
		LevelPosition_t	 uM29LevelPosition;
		LevelLevel_t	 uM30LevelLevel;
		LevelLevel_t	 uM31LevelLevel;
		LevelLevel_t	 uM32LevelLevel;
		NULL_t	 uM33NULL;
		Level_t	 uM34Level;
		Level_t	 uM35Level;
		Level_t	 uM36Level;
		Level_t	 uM37Level;
		Level_t	 uM38Level;
		Level_t	 uM39Level;
		NULL_t	 uM40NULL;
		NULL_t	 uM41NULL;
		PositionLevel_t	 uM42PositionLevel;
		PositionLevel_t	 uM43PositionLevel;
		PositionLevel_t	 uM44PositionLevel;
		PositionLevel_t	 uM45PositionLevel;
		PositionLevel_t	 uM46PositionLevel;
		PositionLevel_t	 uM47PositionLevel;
		PositionLevel_t	 uM48PositionLevel;
		PositionLevel_t	 uM49PositionLevel;
		PositionLevelLevel_t	 uM50PositionLevelLevel;
		PositionTime_t	 uM51PositionTime;
		PositionTime_t	 uM52PositionTime;
		PositionTime_t	 uM53PositionTime;
		PositionTimeTime_t	 uM54PositionTimeTime;
		PositionSpeed_t	 uM55PositionSpeed;
		PositionSpeed_t	 uM56PositionSpeed;
		PositionSpeed_t	 uM57PositionSpeed;
		PositionTimeLevel_t	 uM58PositionTimeLevel;
		PositionTimeLevel_t	 uM59PositionTimeLevel;
		PositionTimeLevel_t	 uM60PositionTimeLevel;
		PositionLevelSpeed_t	 uM61PositionLevelSpeed;
		TimePositionLevel_t	 uM62TimePositionLevel;
		TimePositionLevelSpeed_t	 uM63TimePositionLevelSpeed;
		DistanceSpecifiedDirection_t	 uM64DistanceSpecifiedDirection;
		PositionDistanceSpecifiedDirection_t	 uM65PositionDistanceSpecifiedDirection;
		TimeDistanceSpecifiedDirection_t	 uM66TimeDistanceSpecifiedDirection;
		NULL_t	 uM67NULL;
		Position_t	 uM68Position;
		Time_t	 uM69Time;
		Position_t	 uM70Position;
		Time_t	 uM71Time;
		NULL_t	 uM72NULL;
		DepartureClearance_t	 uM73DepartureClearance;
		Position_t	 uM74Position;
		Position_t	 uM75Position;
		TimePosition_t	 uM76TimePosition;
		PositionPosition_t	 uM77PositionPosition;
		LevelPosition_t	 uM78LevelPosition;
		PositionRouteClearanceIndex_t	 uM79PositionRouteClearance;
		RouteClearanceIndex_t	 uM80RouteClearance;
		ProcedureName_t	 uM81ProcedureName;
		DistanceSpecifiedDirection_t	 uM82DistanceSpecifiedDirection;
		PositionRouteClearanceIndex_t	 uM83PositionRouteClearance;
		PositionProcedureName_t	 uM84PositionProcedureName;
		RouteClearanceIndex_t	 uM85RouteClearance;
		PositionRouteClearanceIndex_t	 uM86PositionRouteClearance;
		Position_t	 uM87Position;
		PositionPosition_t	 uM88PositionPosition;
		TimePosition_t	 uM89TimePosition;
		LevelPosition_t	 uM90LevelPosition;
		HoldClearance_t	 uM91HoldClearance;
		PositionLevel_t	 uM92PositionLevel;
		Time_t	 uM93Time;
		DirectionDegrees_t	 uM94DirectionDegrees;
		DirectionDegrees_t	 uM95DirectionDegrees;
		NULL_t	 uM96NULL;
		PositionDegrees_t	 uM97PositionDegrees;
		DirectionDegrees_t	 uM98DirectionDegrees;
		ProcedureName_t	 uM99ProcedureName;
		TimeSpeed_t	 uM100TimeSpeed;
		PositionSpeed_t	 uM101PositionSpeed;
		LevelSpeed_t	 uM102LevelSpeed;
		TimeSpeedSpeed_t	 uM103TimeSpeedSpeed;
		PositionSpeedSpeed_t	 uM104PositionSpeedSpeed;
		LevelSpeedSpeed_t	 uM105LevelSpeedSpeed;
		Speed_t	 uM106Speed;
		NULL_t	 uM107NULL;
		Speed_t	 uM108Speed;
		Speed_t	 uM109Speed;
		SpeedSpeed_t	 uM110SpeedSpeed;
		Speed_t	 uM111Speed;
		Speed_t	 uM112Speed;
		Speed_t	 uM113Speed;
		Speed_t	 uM114Speed;
		Speed_t	 uM115Speed;
		NULL_t	 uM116NULL;
		UnitNameFrequency_t	 uM117UnitNameFrequency;
		PositionUnitNameFrequency_t	 uM118PositionUnitNameFrequency;
		TimeUnitNameFrequency_t	 uM119TimeUnitNameFrequency;
		UnitNameFrequency_t	 uM120UnitNameFrequency;
		PositionUnitNameFrequency_t	 uM121PositionUnitNameFrequency;
		TimeUnitNameFrequency_t	 uM122TimeUnitNameFrequency;
		Code_t	 uM123Code;
		NULL_t	 uM124NULL;
		NULL_t	 uM125NULL;
		NULL_t	 uM126NULL;
		NULL_t	 uM127NULL;
		Level_t	 uM128Level;
		Level_t	 uM129Level;
		Position_t	 uM130Position;
		NULL_t	 uM131NULL;
		NULL_t	 uM132NULL;
		NULL_t	 uM133NULL;
		SpeedTypeSpeedTypeSpeedType_t	 uM134SpeedTypeSpeedTypeSpeedType;
		NULL_t	 uM135NULL;
		NULL_t	 uM136NULL;
		NULL_t	 uM137NULL;
		NULL_t	 uM138NULL;
		NULL_t	 uM139NULL;
		NULL_t	 uM140NULL;
		NULL_t	 uM141NULL;
		NULL_t	 uM142NULL;
		NULL_t	 uM143NULL;
		NULL_t	 uM144NULL;
		NULL_t	 uM145NULL;
		NULL_t	 uM146NULL;
		NULL_t	 uM147NULL;
		Level_t	 uM148Level;
		LevelPosition_t	 uM149LevelPosition;
		LevelTime_t	 uM150LevelTime;
		Speed_t	 uM151Speed;
		DistanceSpecifiedDirection_t	 uM152DistanceSpecifiedDirection;
		Altimeter_t	 uM153Altimeter;
		NULL_t	 uM154NULL;
		Position_t	 uM155Position;
		NULL_t	 uM156NULL;
		Frequency_t	 uM157Frequency;
		ATISCode_t	 uM158AtisCode;
		ErrorInformation_t	 uM159ErrorInformation;
		Facility_t	 uM160Facility;
		NULL_t	 uM161NULL;
		NULL_t	 uM162NULL;
		FacilityDesignation_t	 uM163FacilityDesignation;
		NULL_t	 uM164NULL;
		NULL_t	 uM165NULL;
		TrafficType_t	 uM166TrafficType;
		NULL_t	 uM167NULL;
		NULL_t	 uM168NULL;
		FreeText_t	 uM169FreeText;
		FreeText_t	 uM170FreeText;
		VerticalRate_t	 uM171VerticalRate;
		VerticalRate_t	 uM172VerticalRate;
		VerticalRate_t	 uM173VerticalRate;
		VerticalRate_t	 uM174VerticalRate;
		Level_t	 uM175Level;
		NULL_t	 uM176NULL;
		NULL_t	 uM177NULL;
		NULL_t	 uM178NULL;
		NULL_t	 uM179NULL;
		LevelLevel_t	 uM180LevelLevel;
		ToFromPosition_t	 uM181ToFromPosition;
		NULL_t	 uM182NULL;
		FreeText_t	 uM183FreeText;
		TimeToFromPosition_t	 uM184TimeToFromPosition;
		PositionLevel_t	 uM185PositionLevel;
		PositionLevel_t	 uM186PositionLevel;
		FreeText_t	 uM187FreeText;
		PositionSpeed_t	 uM188PositionSpeed;
		Speed_t	 uM189Speed;
		Degrees_t	 uM190Degrees;
		NULL_t	 uM191NULL;
		LevelTime_t	 uM192LevelTime;
		NULL_t	 uM193NULL;
		FreeText_t	 uM194FreeText;
		FreeText_t	 uM195FreeText;
		FreeText_t	 uM196FreeText;
		FreeText_t	 uM197FreeText;
		FreeText_t	 uM198FreeText;
		FreeText_t	 uM199FreeText;
		NULL_t	 uM200NULL;
		NULL_t	 uM201NULL;
		NULL_t	 uM202NULL;
		FreeText_t	 uM203FreeText;
		FreeText_t	 uM204FreeText;
		FreeText_t	 uM205FreeText;
		FreeText_t	 uM206FreeText;
		FreeText_t	 uM207FreeText;
		FreeText_t	 uM208FreeText;
		LevelPosition_t	 uM209LevelPosition;
		Position_t	 uM210Position;
		NULL_t	 uM211NULL;
		FacilityDesignationATISCode_t	 uM212FacilityDesignationATISCode;
		FacilityDesignationAltimeter_t	 uM213FacilityDesignationAltimeter;
		RunwayRVR_t	 uM214RunwayRVR;
		DirectionDegrees_t	 uM215DirectionDegrees;
		NULL_t	 uM216NULL;
		NULL_t	 uM217NULL;
		NULL_t	 uM218NULL;
		Level_t	 uM219Level;
		Level_t	 uM220Level;
		Degrees_t	 uM221Degrees;
		NULL_t	 uM222NULL;
		NULL_t	 uM223NULL;
		NULL_t	 uM224NULL;
		NULL_t	 uM225NULL;
		Time_t	 uM226Time;
		NULL_t	 uM227NULL;
		Position_t	 uM228Position;
		NULL_t	 uM229NULL;
		NULL_t	 uM230NULL;
		NULL_t	 uM231NULL;
		NULL_t	 uM232NULL;
		NULL_t	 uM233NULL;
		NULL_t	 uM234NULL;
		NULL_t	 uM235NULL;
		NULL_t	 uM236NULL;
		NULL_t	 uM237NULL;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATCUplinkMsgElementId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATCUplinkMsgElementId;

#ifdef __cplusplus
}
#endif

#endif	/* _ATCUplinkMsgElementId_H_ */
#include "asn_internal.h"
