/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "ATCUplinkRouteClearanceConstrainedData.h"

static asn_TYPE_member_t asn_MBR_ATCUplinkRouteClearanceConstrainedData_1[] = {
	{ ATF_POINTER, 3, offsetof(struct ATCUplinkRouteClearanceConstrainedData, routeClearanceData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RouteClearanceSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"routeClearanceData"
		},
	{ ATF_POINTER, 2, offsetof(struct ATCUplinkRouteClearanceConstrainedData, routeClearanceDataR),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RouteClearanceR,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"routeClearanceDataR"
		},
	{ ATF_POINTER, 1, offsetof(struct ATCUplinkRouteClearanceConstrainedData, routeTaxiData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TaxiRoute,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"routeTaxiData"
		},
};
static const int asn_MAP_ATCUplinkRouteClearanceConstrainedData_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_ATCUplinkRouteClearanceConstrainedData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ATCUplinkRouteClearanceConstrainedData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* routeClearanceData */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* routeClearanceDataR */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* routeTaxiData */
};
static asn_SEQUENCE_specifics_t asn_SPC_ATCUplinkRouteClearanceConstrainedData_specs_1 = {
	sizeof(struct ATCUplinkRouteClearanceConstrainedData),
	offsetof(struct ATCUplinkRouteClearanceConstrainedData, _asn_ctx),
	asn_MAP_ATCUplinkRouteClearanceConstrainedData_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ATCUplinkRouteClearanceConstrainedData_oms_1,	/* Optional members */
	1, 2,	/* Root/Additions */
	0,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ATCUplinkRouteClearanceConstrainedData = {
	"ATCUplinkRouteClearanceConstrainedData",
	"ATCUplinkRouteClearanceConstrainedData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ATCUplinkRouteClearanceConstrainedData_tags_1,
	sizeof(asn_DEF_ATCUplinkRouteClearanceConstrainedData_tags_1)
		/sizeof(asn_DEF_ATCUplinkRouteClearanceConstrainedData_tags_1[0]), /* 1 */
	asn_DEF_ATCUplinkRouteClearanceConstrainedData_tags_1,	/* Same as above */
	sizeof(asn_DEF_ATCUplinkRouteClearanceConstrainedData_tags_1)
		/sizeof(asn_DEF_ATCUplinkRouteClearanceConstrainedData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ATCUplinkRouteClearanceConstrainedData_1,
	3,	/* Elements count */
	&asn_SPC_ATCUplinkRouteClearanceConstrainedData_specs_1	/* Additional specs */
};

