/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ATWAlongTrackWaypointR_H_
#define	_ATWAlongTrackWaypointR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PositionR.h"
#include "ATWDistance.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WaypointSpeedConstraint;
struct WaypointLevelConstraint;

/* ATWAlongTrackWaypointR */
typedef struct ATWAlongTrackWaypointR {
	PositionR_t	 position;
	ATWDistance_t	 aTWDistance;
	struct WaypointSpeedConstraint	*speed	/* OPTIONAL */;
	struct WaypointLevelConstraint	*level	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATWAlongTrackWaypointR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATWAlongTrackWaypointR;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WaypointSpeedConstraint.h"
#include "WaypointLevelConstraint.h"

#endif	/* _ATWAlongTrackWaypointR_H_ */
#include "asn_internal.h"
