/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ClearanceTypeR_H_
#define	_ClearanceTypeR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ClearanceTypeR {
	ClearanceTypeR_approach	= 0,
	ClearanceTypeR_departure	= 1,
	ClearanceTypeR_further	= 2,
	ClearanceTypeR_startup	= 3,
	ClearanceTypeR_pushback	= 4,
	ClearanceTypeR_taxi	= 5,
	ClearanceTypeR_oceanic	= 6
	/*
	 * Enumeration is extensible
	 */
} e_ClearanceTypeR;

/* ClearanceTypeR */
typedef long	 ClearanceTypeR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ClearanceTypeR;
asn_struct_free_f ClearanceTypeR_free;
asn_struct_print_f ClearanceTypeR_print;
asn_constr_check_f ClearanceTypeR_constraint;
ber_type_decoder_f ClearanceTypeR_decode_ber;
der_type_encoder_f ClearanceTypeR_encode_der;
xer_type_decoder_f ClearanceTypeR_decode_xer;
xer_type_encoder_f ClearanceTypeR_encode_xer;
per_type_decoder_f ClearanceTypeR_decode_uper;
per_type_encoder_f ClearanceTypeR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ClearanceTypeR_H_ */
#include "asn_internal.h"
