/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CMMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_CMContactRequest_H_
#define	_CMContactRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FacilityDesignation.h"
#include "LongTsap.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CMContactRequest */
typedef struct CMContactRequest {
	FacilityDesignation_t	 facilityDesignation;
	LongTsap_t	 address;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CMContactRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMContactRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _CMContactRequest_H_ */
#include "asn_internal.h"
