/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CMMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "CMGroundMessage.h"

static asn_per_constraints_t asn_PER_type_CMGroundMessage_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_CMGroundMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CMGroundMessage, choice.cmLogonResponse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CMLogonResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cmLogonResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CMGroundMessage, choice.cmUpdate),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CMUpdate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cmUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CMGroundMessage, choice.cmContactRequest),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CMContactRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cmContactRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CMGroundMessage, choice.cmForwardRequest),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CMForwardRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cmForwardRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CMGroundMessage, choice.cmAbortReason),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CMAbortReason,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cmAbortReason"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CMGroundMessage, choice.cmForwardResponse),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CMForwardResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cmForwardResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CMGroundMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cmLogonResponse */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cmUpdate */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cmContactRequest */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cmForwardRequest */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* cmAbortReason */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* cmForwardResponse */
};
static asn_CHOICE_specifics_t asn_SPC_CMGroundMessage_specs_1 = {
	sizeof(struct CMGroundMessage),
	offsetof(struct CMGroundMessage, _asn_ctx),
	offsetof(struct CMGroundMessage, present),
	sizeof(((struct CMGroundMessage *)0)->present),
	asn_MAP_CMGroundMessage_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	6	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CMGroundMessage = {
	"CMGroundMessage",
	"CMGroundMessage",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_CMGroundMessage_constr_1,
	asn_MBR_CMGroundMessage_1,
	6,	/* Elements count */
	&asn_SPC_CMGroundMessage_specs_1	/* Additional specs */
};

