/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CMMessageSetVersion1"
 * 	found in "atn-cm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_CMGroundMessage_H_
#define	_CMGroundMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CMLogonResponse.h"
#include "CMUpdate.h"
#include "CMContactRequest.h"
#include "CMForwardRequest.h"
#include "CMAbortReason.h"
#include "CMForwardResponse.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CMGroundMessage_PR {
	CMGroundMessage_PR_NOTHING,	/* No components present */
	CMGroundMessage_PR_cmLogonResponse,
	CMGroundMessage_PR_cmUpdate,
	CMGroundMessage_PR_cmContactRequest,
	CMGroundMessage_PR_cmForwardRequest,
	CMGroundMessage_PR_cmAbortReason,
	CMGroundMessage_PR_cmForwardResponse,
	/* Extensions may appear below */
	
} CMGroundMessage_PR;

/* CMGroundMessage */
typedef struct CMGroundMessage {
	CMGroundMessage_PR present;
	union CMGroundMessage_u {
		CMLogonResponse_t	 cmLogonResponse;
		CMUpdate_t	 cmUpdate;
		CMContactRequest_t	 cmContactRequest;
		CMForwardRequest_t	 cmForwardRequest;
		CMAbortReason_t	 cmAbortReason;
		CMForwardResponse_t	 cmForwardResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CMGroundMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMGroundMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _CMGroundMessage_H_ */
#include "asn_internal.h"
