/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_Code_H_
#define	_Code_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CodeOctalDigit.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Code */
typedef struct Code {
	A_SEQUENCE_OF(CodeOctalDigit_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Code_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Code;

#ifdef __cplusplus
}
#endif

#endif	/* _Code_H_ */
#include "asn_internal.h"
