/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCAPDUsVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_CPDLCProviderAbortReason_H_
#define	_CPDLCProviderAbortReason_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CPDLCProviderAbortReason {
	CPDLCProviderAbortReason_timer_expired	= 0,
	CPDLCProviderAbortReason_undefined_error	= 1,
	CPDLCProviderAbortReason_invalid_PDU	= 2,
	CPDLCProviderAbortReason_protocol_error	= 3,
	CPDLCProviderAbortReason_communication_service_error	= 4,
	CPDLCProviderAbortReason_communication_service_failure	= 5,
	CPDLCProviderAbortReason_invalid_QOS_parameter	= 6,
	CPDLCProviderAbortReason_expected_PDU_missing	= 7
	/*
	 * Enumeration is extensible
	 */
} e_CPDLCProviderAbortReason;

/* CPDLCProviderAbortReason */
typedef long	 CPDLCProviderAbortReason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CPDLCProviderAbortReason;
asn_struct_free_f CPDLCProviderAbortReason_free;
asn_struct_print_f CPDLCProviderAbortReason_print;
asn_constr_check_f CPDLCProviderAbortReason_constraint;
ber_type_decoder_f CPDLCProviderAbortReason_decode_ber;
der_type_encoder_f CPDLCProviderAbortReason_encode_der;
xer_type_decoder_f CPDLCProviderAbortReason_decode_xer;
xer_type_encoder_f CPDLCProviderAbortReason_encode_xer;
per_type_decoder_f CPDLCProviderAbortReason_decode_uper;
per_type_encoder_f CPDLCProviderAbortReason_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CPDLCProviderAbortReason_H_ */
#include "asn_internal.h"
