/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_DemandContractRequest_H_
#define	_DemandContractRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ContractNumber.h"
#include "NULL.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MetInfoRequest;
struct EPPWindow;
struct TOARangeRequest;

/* DemandContractRequest */
typedef struct DemandContractRequest {
	ContractNumber_t	 contract_number;
	NULL_t	*projected_profile	/* OPTIONAL */;
	NULL_t	*ground_vector	/* OPTIONAL */;
	NULL_t	*air_vector	/* OPTIONAL */;
	struct MetInfoRequest	*met_info	/* OPTIONAL */;
	struct EPPWindow	*extended_projected_profile	/* OPTIONAL */;
	struct TOARangeRequest	*toa_range	/* OPTIONAL */;
	NULL_t	*speed_schedule_profile	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	NULL_t	*rnp_profile	/* OPTIONAL */;
	NULL_t	*planned_final_approach_speed	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DemandContractRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DemandContractRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MetInfoRequest.h"
#include "EPPWindow.h"
#include "TOARangeRequest.h"

#endif	/* _DemandContractRequest_H_ */
#include "asn_internal.h"
