/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_DepartureLevelValue_H_
#define	_DepartureLevelValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LevelS.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DepartureUntilConstraint;

/* DepartureLevelValue */
typedef struct DepartureLevelValue {
	LevelS_t	 level;
	struct DepartureUntilConstraint	*untilConstraint	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DepartureLevelValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DepartureLevelValue;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DepartureUntilConstraint.h"

#endif	/* _DepartureLevelValue_H_ */
#include "asn_internal.h"
