/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_DirectionCompass_H_
#define	_DirectionCompass_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DirectionCompass {
	DirectionCompass_north	= 0,
	DirectionCompass_south	= 1,
	DirectionCompass_east	= 2,
	DirectionCompass_west	= 3,
	DirectionCompass_northEast	= 4,
	DirectionCompass_northWest	= 5,
	DirectionCompass_southEast	= 6,
	DirectionCompass_southWest	= 7
} e_DirectionCompass;

/* DirectionCompass */
typedef long	 DirectionCompass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DirectionCompass;
asn_struct_free_f DirectionCompass_free;
asn_struct_print_f DirectionCompass_print;
asn_constr_check_f DirectionCompass_constraint;
ber_type_decoder_f DirectionCompass_decode_ber;
der_type_encoder_f DirectionCompass_encode_der;
xer_type_decoder_f DirectionCompass_decode_xer;
xer_type_encoder_f DirectionCompass_encode_xer;
per_type_decoder_f DirectionCompass_decode_uper;
per_type_encoder_f DirectionCompass_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DirectionCompass_H_ */
#include "asn_internal.h"
