/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_DMVersionNumber_H_
#define	_DMVersionNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DMVersionNumber */
typedef long	 DMVersionNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DMVersionNumber;
asn_struct_free_f DMVersionNumber_free;
asn_struct_print_f DMVersionNumber_print;
asn_constr_check_f DMVersionNumber_constraint;
ber_type_decoder_f DMVersionNumber_decode_ber;
der_type_encoder_f DMVersionNumber_encode_der;
xer_type_decoder_f DMVersionNumber_decode_xer;
xer_type_encoder_f DMVersionNumber_encode_xer;
per_type_decoder_f DMVersionNumber_decode_uper;
per_type_encoder_f DMVersionNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DMVersionNumber_H_ */
#include "asn_internal.h"
