/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ECRWaypointChange_H_
#define	_ECRWaypointChange_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ECRWaypointChange */
typedef NULL_t	 ECRWaypointChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECRWaypointChange;
asn_struct_free_f ECRWaypointChange_free;
asn_struct_print_f ECRWaypointChange_print;
asn_constr_check_f ECRWaypointChange_constraint;
ber_type_decoder_f ECRWaypointChange_decode_ber;
der_type_encoder_f ECRWaypointChange_encode_der;
xer_type_decoder_f ECRWaypointChange_decode_xer;
xer_type_encoder_f ECRWaypointChange_encode_xer;
per_type_decoder_f ECRWaypointChange_decode_uper;
per_type_encoder_f ECRWaypointChange_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ECRWaypointChange_H_ */
#include "asn_internal.h"
