/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "EPPEventChange.h"

static asn_TYPE_member_t asn_MBR_EPPEventChange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPPEventChange, epp_event_window),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EPPWindow,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"epp-event-window"
		},
	{ ATF_POINTER, 3, offsetof(struct EPPEventChange, epp_flight_plan_change),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EPPFlightPlanChangeRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"epp-flight-plan-change"
		},
	{ ATF_POINTER, 2, offsetof(struct EPPEventChange, epp_next_waypoint_in_horizon),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EPPNextWptInHorizonRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"epp-next-waypoint-in-horizon"
		},
	{ ATF_POINTER, 1, offsetof(struct EPPEventChange, epp_tolerance),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EPPToleranceChange,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"epp-tolerance"
		},
};
static const int asn_MAP_EPPEventChange_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_EPPEventChange_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EPPEventChange_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* epp-event-window */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* epp-flight-plan-change */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* epp-next-waypoint-in-horizon */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* epp-tolerance */
};
static asn_SEQUENCE_specifics_t asn_SPC_EPPEventChange_specs_1 = {
	sizeof(struct EPPEventChange),
	offsetof(struct EPPEventChange, _asn_ctx),
	asn_MAP_EPPEventChange_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_EPPEventChange_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EPPEventChange = {
	"EPPEventChange",
	"EPPEventChange",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EPPEventChange_tags_1,
	sizeof(asn_DEF_EPPEventChange_tags_1)
		/sizeof(asn_DEF_EPPEventChange_tags_1[0]), /* 1 */
	asn_DEF_EPPEventChange_tags_1,	/* Same as above */
	sizeof(asn_DEF_EPPEventChange_tags_1)
		/sizeof(asn_DEF_EPPEventChange_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EPPEventChange_1,
	4,	/* Elements count */
	&asn_SPC_EPPEventChange_specs_1	/* Additional specs */
};

