/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_EPPEventChange_H_
#define	_EPPEventChange_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EPPWindow.h"
#include "EPPFlightPlanChangeRequest.h"
#include "EPPNextWptInHorizonRequest.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EPPToleranceChange;

/* EPPEventChange */
typedef struct EPPEventChange {
	EPPWindow_t	 epp_event_window;
	EPPFlightPlanChangeRequest_t	*epp_flight_plan_change	/* OPTIONAL */;
	EPPNextWptInHorizonRequest_t	*epp_next_waypoint_in_horizon	/* OPTIONAL */;
	struct EPPToleranceChange	*epp_tolerance	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EPPEventChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EPPEventChange;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EPPToleranceChange.h"

#endif	/* _EPPEventChange_H_ */
#include "asn_internal.h"
