/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_EPPWindow_H_
#define	_EPPWindow_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EPPWindow_PR {
	EPPWindow_PR_NOTHING,	/* No components present */
	EPPWindow_PR_time_interval,
	EPPWindow_PR_number_of_way_points
} EPPWindow_PR;

/* EPPWindow */
typedef struct EPPWindow {
	EPPWindow_PR present;
	union EPPWindow_u {
		long	 time_interval;
		long	 number_of_way_points;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EPPWindow_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EPPWindow;

#ifdef __cplusplus
}
#endif

#endif	/* _EPPWindow_H_ */
#include "asn_internal.h"
