/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ErrorInformationR_H_
#define	_ErrorInformationR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ErrorInformationR {
	ErrorInformationR_unrecognizedMsgReferenceNumber	= 0,
	ErrorInformationR_undefinedError	= 1,
	ErrorInformationR_insufficientResources	= 2,
	ErrorInformationR_validationFailure	= 3
	/*
	 * Enumeration is extensible
	 */
} e_ErrorInformationR;

/* ErrorInformationR */
typedef long	 ErrorInformationR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ErrorInformationR;
asn_struct_free_f ErrorInformationR_free;
asn_struct_print_f ErrorInformationR_print;
asn_constr_check_f ErrorInformationR_constraint;
ber_type_decoder_f ErrorInformationR_decode_ber;
der_type_encoder_f ErrorInformationR_encode_der;
xer_type_decoder_f ErrorInformationR_decode_xer;
xer_type_encoder_f ErrorInformationR_encode_xer;
per_type_decoder_f ErrorInformationR_decode_uper;
per_type_encoder_f ErrorInformationR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ErrorInformationR_H_ */
#include "asn_internal.h"
