/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_EventTypeNotSupported_H_
#define	_EventTypeNotSupported_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EventTypeNotSupported {
	EventTypeNotSupported_lateral_deviation	= 0,
	EventTypeNotSupported_vertical_rate_deviation	= 1,
	EventTypeNotSupported_level_range_deviation	= 2,
	EventTypeNotSupported_way_point_change	= 3,
	EventTypeNotSupported_air_speed_change	= 4,
	EventTypeNotSupported_ground_speed_change	= 5,
	EventTypeNotSupported_epp_flight_plan_change	= 6,
	EventTypeNotSupported_epp_next_waypoint_in_horizon	= 7,
	EventTypeNotSupported_epp_tolerance_event	= 8,
	EventTypeNotSupported_rta_status_change	= 9,
	EventTypeNotSupported_fom_change	= 10,
	EventTypeNotSupported_level_change	= 11,
	EventTypeNotSupported_vertical_clearance_deviation	= 12,
	EventTypeNotSupported_airspeed_range_deviation	= 13,
	EventTypeNotSupported_turbulence_deviation	= 14,
	EventTypeNotSupported_rnp_not_met	= 15,
	EventTypeNotSupported_planned_final_approach_speed_change	= 16
} e_EventTypeNotSupported;

/* EventTypeNotSupported */
typedef BIT_STRING_t	 EventTypeNotSupported_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventTypeNotSupported;
asn_struct_free_f EventTypeNotSupported_free;
asn_struct_print_f EventTypeNotSupported_print;
asn_constr_check_f EventTypeNotSupported_constraint;
ber_type_decoder_f EventTypeNotSupported_decode_ber;
der_type_encoder_f EventTypeNotSupported_encode_der;
xer_type_decoder_f EventTypeNotSupported_decode_xer;
xer_type_encoder_f EventTypeNotSupported_encode_xer;
per_type_decoder_f EventTypeNotSupported_decode_uper;
per_type_encoder_f EventTypeNotSupported_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EventTypeNotSupported_H_ */
#include "asn_internal.h"
