/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "ExtendedProjectedProfile.h"

static int
memb_way_point_sequence_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 128)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_way_point_sequence_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 7,  7,  1,  128 }	/* (SIZE(1..128)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_way_point_sequence_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 7,  7,  1,  128 }	/* (SIZE(1..128)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Member_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, latitude),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ADSv2Latitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"latitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, longitude),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ADSv2Longitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"longitude"
		},
	{ ATF_POINTER, 9, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, level),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EPPLevel,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"level"
		},
	{ ATF_POINTER, 8, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, name),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_WaypointName,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"name"
		},
	{ ATF_POINTER, 7, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, estimated_time),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ETA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"estimated-time"
		},
	{ ATF_POINTER, 6, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, estimated_speed),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SpeedIASMach,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"estimated-speed"
		},
	{ ATF_POINTER, 5, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, vertical_type),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VerticalType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"vertical-type"
		},
	{ ATF_POINTER, 4, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, lateral_type),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LateralType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lateral-type"
		},
	{ ATF_POINTER, 3, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, level_constraint),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LevelConstraint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"level-constraint"
		},
	{ ATF_POINTER, 2, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, speed_contraint),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SpeedConstraint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"speed-contraint"
		},
	{ ATF_POINTER, 1, offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, time_constraint),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RTA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"time-constraint"
		},
};
static const int asn_MAP_Member_oms_4[] = { 2, 3, 4, 5, 6, 7, 8, 9, 10 };
static const ber_tlv_tag_t asn_DEF_Member_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* latitude */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* longitude */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* level */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* estimated-time */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* estimated-speed */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* vertical-type */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* lateral-type */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* level-constraint */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* speed-contraint */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 } /* time-constraint */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_4 = {
	sizeof(struct ExtendedProjectedProfile__way_point_sequence__Member),
	offsetof(struct ExtendedProjectedProfile__way_point_sequence__Member, _asn_ctx),
	asn_MAP_Member_tag2el_4,
	11,	/* Count of tags in the map */
	asn_MAP_Member_oms_4,	/* Optional members */
	9, 0,	/* Root/Additions */
	10,	/* Start extensions */
	12	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_4 = {
	"SEQUENCE",
	"SEQUENCE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Member_tags_4,
	sizeof(asn_DEF_Member_tags_4)
		/sizeof(asn_DEF_Member_tags_4[0]), /* 1 */
	asn_DEF_Member_tags_4,	/* Same as above */
	sizeof(asn_DEF_Member_tags_4)
		/sizeof(asn_DEF_Member_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Member_4,
	11,	/* Elements count */
	&asn_SPC_Member_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_way_point_sequence_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_way_point_sequence_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_way_point_sequence_specs_3 = {
	sizeof(struct ExtendedProjectedProfile__way_point_sequence),
	offsetof(struct ExtendedProjectedProfile__way_point_sequence, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_way_point_sequence_3 = {
	"way-point-sequence",
	"way-point-sequence",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_way_point_sequence_tags_3,
	sizeof(asn_DEF_way_point_sequence_tags_3)
		/sizeof(asn_DEF_way_point_sequence_tags_3[0]), /* 2 */
	asn_DEF_way_point_sequence_tags_3,	/* Same as above */
	sizeof(asn_DEF_way_point_sequence_tags_3)
		/sizeof(asn_DEF_way_point_sequence_tags_3[0]), /* 2 */
	&asn_PER_type_way_point_sequence_constr_3,
	asn_MBR_way_point_sequence_3,
	1,	/* Single element */
	&asn_SPC_way_point_sequence_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ExtendedProjectedProfile_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedProjectedProfile, computation_time),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ADSv2DateTimeGroup,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"computation-time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedProjectedProfile, way_point_sequence),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_way_point_sequence_3,
		memb_way_point_sequence_constraint_1,
		&asn_PER_memb_way_point_sequence_constr_3,
		0,
		"way-point-sequence"
		},
	{ ATF_POINTER, 2, offsetof(struct ExtendedProjectedProfile, current_gross_mass),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GrossMass,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"current-gross-mass"
		},
	{ ATF_POINTER, 1, offsetof(struct ExtendedProjectedProfile, trajectory_intent_status),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TrajectoryIntentStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"trajectory-intent-status"
		},
};
static const int asn_MAP_ExtendedProjectedProfile_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_ExtendedProjectedProfile_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ExtendedProjectedProfile_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* computation-time */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* way-point-sequence */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* current-gross-mass */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* trajectory-intent-status */
};
static asn_SEQUENCE_specifics_t asn_SPC_ExtendedProjectedProfile_specs_1 = {
	sizeof(struct ExtendedProjectedProfile),
	offsetof(struct ExtendedProjectedProfile, _asn_ctx),
	asn_MAP_ExtendedProjectedProfile_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ExtendedProjectedProfile_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ExtendedProjectedProfile = {
	"ExtendedProjectedProfile",
	"ExtendedProjectedProfile",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ExtendedProjectedProfile_tags_1,
	sizeof(asn_DEF_ExtendedProjectedProfile_tags_1)
		/sizeof(asn_DEF_ExtendedProjectedProfile_tags_1[0]), /* 1 */
	asn_DEF_ExtendedProjectedProfile_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExtendedProjectedProfile_tags_1)
		/sizeof(asn_DEF_ExtendedProjectedProfile_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ExtendedProjectedProfile_1,
	4,	/* Elements count */
	&asn_SPC_ExtendedProjectedProfile_specs_1	/* Additional specs */
};

