/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ExtendedProjectedProfile_H_
#define	_ExtendedProjectedProfile_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ADSv2DateTimeGroup.h"
#include "GrossMass.h"
#include "asn_SEQUENCE_OF.h"
#include "ADSv2Latitude.h"
#include "ADSv2Longitude.h"
#include "WaypointName.h"
#include "VerticalType.h"
#include "constr_SEQUENCE.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TrajectoryIntentStatus;
struct EPPLevel;
struct Timesec;
struct SpeedIASMach;
struct LateralType;
struct LevelConstraint;
struct SpeedConstraint;
struct RTA;

/* ExtendedProjectedProfile */
typedef struct ExtendedProjectedProfile {
	ADSv2DateTimeGroup_t	 computation_time;
	struct ExtendedProjectedProfile__way_point_sequence {
		A_SEQUENCE_OF(struct ExtendedProjectedProfile__way_point_sequence__Member {
			ADSv2Latitude_t	 latitude;
			ADSv2Longitude_t	 longitude;
			struct EPPLevel	*level	/* OPTIONAL */;
			WaypointName_t	*name	/* OPTIONAL */;
			struct Timesec	*estimated_time	/* OPTIONAL */;
			struct SpeedIASMach	*estimated_speed	/* OPTIONAL */;
			VerticalType_t	*vertical_type	/* OPTIONAL */;
			struct LateralType	*lateral_type	/* OPTIONAL */;
			struct LevelConstraint	*level_constraint	/* OPTIONAL */;
			struct SpeedConstraint	*speed_contraint	/* OPTIONAL */;
			struct RTA	*time_constraint	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} way_point_sequence;
	GrossMass_t	*current_gross_mass	/* OPTIONAL */;
	struct TrajectoryIntentStatus	*trajectory_intent_status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedProjectedProfile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedProjectedProfile;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TrajectoryIntentStatus.h"
#include "EPPLevel.h"
#include "ETA.h"
#include "SpeedIASMach.h"
#include "LateralType.h"
#include "LevelConstraint.h"
#include "SpeedConstraint.h"
#include "RTA.h"

#endif	/* _ExtendedProjectedProfile_H_ */
#include "asn_internal.h"
