/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_FacilityFunction_H_
#define	_FacilityFunction_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FacilityFunction {
	FacilityFunction_center	= 0,
	FacilityFunction_approach	= 1,
	FacilityFunction_tower	= 2,
	FacilityFunction_final	= 3,
	FacilityFunction_groundControl	= 4,
	FacilityFunction_clearanceDelivery	= 5,
	FacilityFunction_departure	= 6,
	FacilityFunction_control	= 7,
	FacilityFunction_radio	= 8
	/*
	 * Enumeration is extensible
	 */
} e_FacilityFunction;

/* FacilityFunction */
typedef long	 FacilityFunction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FacilityFunction;
asn_struct_free_f FacilityFunction_free;
asn_struct_print_f FacilityFunction_print;
asn_constr_check_f FacilityFunction_constraint;
ber_type_decoder_f FacilityFunction_decode_ber;
der_type_encoder_f FacilityFunction_encode_der;
xer_type_decoder_f FacilityFunction_decode_xer;
xer_type_encoder_f FacilityFunction_encode_xer;
per_type_decoder_f FacilityFunction_decode_uper;
per_type_encoder_f FacilityFunction_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FacilityFunction_H_ */
#include <asn_internal.h>
