/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FacingDirection_H_
#define	_FacingDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DirectionCompass.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FacingDirection */
typedef DirectionCompass_t	 FacingDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FacingDirection;
asn_struct_free_f FacingDirection_free;
asn_struct_print_f FacingDirection_print;
asn_constr_check_f FacingDirection_constraint;
ber_type_decoder_f FacingDirection_decode_ber;
der_type_encoder_f FacingDirection_encode_der;
xer_type_decoder_f FacingDirection_decode_xer;
xer_type_encoder_f FacingDirection_encode_xer;
per_type_decoder_f FacingDirection_decode_uper;
per_type_encoder_f FacingDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FacingDirection_H_ */
#include "asn_internal.h"
