/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_Fix_H_
#define	_Fix_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Fix */
typedef IA5String_t	 Fix_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Fix;
asn_struct_free_f Fix_free;
asn_struct_print_f Fix_print;
asn_constr_check_f Fix_constraint;
ber_type_decoder_f Fix_decode_ber;
der_type_encoder_f Fix_encode_der;
xer_type_decoder_f Fix_decode_xer;
xer_type_encoder_f Fix_encode_xer;
per_type_decoder_f Fix_decode_uper;
per_type_encoder_f Fix_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Fix_H_ */
#include "asn_internal.h"
