/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FlightInformation_H_
#define	_FlightInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RouteInformation.h"
#include "LevelsOfFlight.h"
#include "RouteAndLevels.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FlightInformation_PR {
	FlightInformation_PR_NOTHING,	/* No components present */
	FlightInformation_PR_routeOfFlight,
	FlightInformation_PR_levelsOfFlight,
	FlightInformation_PR_routeAndLevels
} FlightInformation_PR;

/* FlightInformation */
typedef struct FlightInformation {
	FlightInformation_PR present;
	union FlightInformation_u {
		RouteInformation_t	 routeOfFlight;
		LevelsOfFlight_t	 levelsOfFlight;
		RouteAndLevels_t	 routeAndLevels;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FlightInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FlightInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _FlightInformation_H_ */
#include "asn_internal.h"
