/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FlightPhaseO_H_
#define	_FlightPhaseO_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NoFlightPhase.h"
#include "FlightPhase.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FlightPhaseO_PR {
	FlightPhaseO_PR_NOTHING,	/* No components present */
	FlightPhaseO_PR_noFlightPhase,
	FlightPhaseO_PR_flightPhase
} FlightPhaseO_PR;

/* FlightPhaseO */
typedef struct FlightPhaseO {
	FlightPhaseO_PR present;
	union FlightPhaseO_u {
		NoFlightPhase_t	 noFlightPhase;
		FlightPhase_t	 flightPhase;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FlightPhaseO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FlightPhaseO;

#ifdef __cplusplus
}
#endif

#endif	/* _FlightPhaseO_H_ */
#include "asn_internal.h"
