/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_GroundLongitude_H_
#define	_GroundLongitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GroundLongitudeDegrees.h"
#include "LongitudeDirection.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GroundLongitude */
typedef struct GroundLongitude {
	GroundLongitudeDegrees_t	 longitude;
	LongitudeDirection_t	 direction;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroundLongitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroundLongitude;

#ifdef __cplusplus
}
#endif

#endif	/* _GroundLongitude_H_ */
#include "asn_internal.h"
