/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_GroundTrack_H_
#define	_GroundTrack_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GroundTrack */
typedef long	 GroundTrack_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroundTrack;
asn_struct_free_f GroundTrack_free;
asn_struct_print_f GroundTrack_print;
asn_constr_check_f GroundTrack_constraint;
ber_type_decoder_f GroundTrack_decode_ber;
der_type_encoder_f GroundTrack_encode_der;
xer_type_decoder_f GroundTrack_decode_xer;
xer_type_encoder_f GroundTrack_encode_xer;
per_type_decoder_f GroundTrack_decode_uper;
per_type_encoder_f GroundTrack_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GroundTrack_H_ */
#include "asn_internal.h"
