/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "GroundLocation.h"

static asn_per_constraints_t asn_PER_type_GroundLocation_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  5,  5,  0,  18 }	/* (0..18,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_GroundLocation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.apron),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Apron,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"apron"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.gate),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Gate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"gate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.stand),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Stand,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"stand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.holdingBay),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_HoldingBay,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"holdingBay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.holdingPoint),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_HoldingPoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"holdingPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.intersection),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Intersection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"intersection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.hangar),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Hangar,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"hangar"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.namedPoint),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NamedPoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"namedPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.ramp),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Ramp,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ramp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.runway),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Runway,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"runway"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.taxilane),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Taxilane,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"taxilane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.taxiway),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Taxiway,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"taxiway"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.terminal),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Terminal,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"terminal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.deicingPosition),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DeicingStopPosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"deicingPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.deicingStopPosition),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DeicingPosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"deicingStopPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.normalExit),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NormalExit,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"normalExit"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.rapidExit),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RapidExit,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rapidExit"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.aircraftLatlong),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GroundLatLong,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aircraftLatlong"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroundLocation, choice.customs),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Customs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"customs"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_GroundLocation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* apron */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gate */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* stand */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* holdingBay */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* holdingPoint */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* intersection */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* hangar */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* namedPoint */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* ramp */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* runway */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* taxilane */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* taxiway */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* terminal */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* deicingPosition */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* deicingStopPosition */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* normalExit */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* rapidExit */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* aircraftLatlong */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 } /* customs */
};
static asn_CHOICE_specifics_t asn_SPC_GroundLocation_specs_1 = {
	sizeof(struct GroundLocation),
	offsetof(struct GroundLocation, _asn_ctx),
	offsetof(struct GroundLocation, present),
	sizeof(((struct GroundLocation *)0)->present),
	asn_MAP_GroundLocation_tag2el_1,
	19,	/* Count of tags in the map */
	0,
	19	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_GroundLocation = {
	"GroundLocation",
	"GroundLocation",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_GroundLocation_constr_1,
	asn_MBR_GroundLocation_1,
	19,	/* Elements count */
	&asn_SPC_GroundLocation_specs_1	/* Additional specs */
};

