/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_HoldatwaypointSpeedLow_H_
#define	_HoldatwaypointSpeedLow_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Speed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HoldatwaypointSpeedLow */
typedef Speed_t	 HoldatwaypointSpeedLow_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HoldatwaypointSpeedLow;
asn_struct_free_f HoldatwaypointSpeedLow_free;
asn_struct_print_f HoldatwaypointSpeedLow_print;
asn_constr_check_f HoldatwaypointSpeedLow_constraint;
ber_type_decoder_f HoldatwaypointSpeedLow_decode_ber;
der_type_encoder_f HoldatwaypointSpeedLow_encode_der;
xer_type_decoder_f HoldatwaypointSpeedLow_decode_xer;
xer_type_encoder_f HoldatwaypointSpeedLow_encode_xer;
per_type_decoder_f HoldatwaypointSpeedLow_decode_uper;
per_type_encoder_f HoldatwaypointSpeedLow_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HoldatwaypointSpeedLow_H_ */
#include "asn_internal.h"
