/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_HoldSpeedLow_H_
#define	_HoldSpeedLow_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Speed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HoldSpeedLow */
typedef Speed_t	 HoldSpeedLow_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HoldSpeedLow;
asn_struct_free_f HoldSpeedLow_free;
asn_struct_print_f HoldSpeedLow_print;
asn_constr_check_f HoldSpeedLow_constraint;
ber_type_decoder_f HoldSpeedLow_decode_ber;
der_type_encoder_f HoldSpeedLow_encode_der;
xer_type_decoder_f HoldSpeedLow_decode_xer;
xer_type_encoder_f HoldSpeedLow_encode_xer;
per_type_decoder_f HoldSpeedLow_decode_uper;
per_type_encoder_f HoldSpeedLow_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HoldSpeedLow_H_ */
#include "asn_internal.h"
