/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "HoldClearance.h"

static asn_TYPE_member_t asn_MBR_HoldClearance_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HoldClearance, position),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HoldClearance, level),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Level,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"level"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HoldClearance, degrees),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Degrees,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"degrees"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HoldClearance, direction),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Direction,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"direction"
		},
	{ ATF_POINTER, 1, offsetof(struct HoldClearance, legType),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LegType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"legType"
		},
};
static const int asn_MAP_HoldClearance_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_HoldClearance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HoldClearance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* position */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* level */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* degrees */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* direction */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* legType */
};
static asn_SEQUENCE_specifics_t asn_SPC_HoldClearance_specs_1 = {
	sizeof(struct HoldClearance),
	offsetof(struct HoldClearance, _asn_ctx),
	asn_MAP_HoldClearance_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_HoldClearance_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_HoldClearance = {
	"HoldClearance",
	"HoldClearance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_HoldClearance_tags_1,
	sizeof(asn_DEF_HoldClearance_tags_1)
		/sizeof(asn_DEF_HoldClearance_tags_1[0]), /* 1 */
	asn_DEF_HoldClearance_tags_1,	/* Same as above */
	sizeof(asn_DEF_HoldClearance_tags_1)
		/sizeof(asn_DEF_HoldClearance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_HoldClearance_1,
	5,	/* Elements count */
	&asn_SPC_HoldClearance_specs_1	/* Additional specs */
};

