/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMADSCAPDUVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_pmadsc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "ICReject.h"

static asn_TYPE_member_t asn_MBR_ICReject_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ICReject, algorithmIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"algorithmIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ICReject, aDSMessage),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ADSMessage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aDSMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ICReject, integrityCheck),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"integrityCheck"
		},
};
static const int asn_MAP_ICReject_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ICReject_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ICReject_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* algorithmIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aDSMessage */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* integrityCheck */
};
static asn_SEQUENCE_specifics_t asn_SPC_ICReject_specs_1 = {
	sizeof(struct ICReject),
	offsetof(struct ICReject, _asn_ctx),
	asn_MAP_ICReject_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ICReject_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ICReject = {
	"ICReject",
	"ICReject",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ICReject_tags_1,
	sizeof(asn_DEF_ICReject_tags_1)
		/sizeof(asn_DEF_ICReject_tags_1[0]), /* 1 */
	asn_DEF_ICReject_tags_1,	/* Same as above */
	sizeof(asn_DEF_ICReject_tags_1)
		/sizeof(asn_DEF_ICReject_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ICReject_1,
	3,	/* Elements count */
	&asn_SPC_ICReject_specs_1	/* Additional specs */
};

