/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMADSCAPDUVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_pmadsc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ICReject_H_
#define	_ICReject_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AlgorithmIdentifier.h"
#include "ADSMessage.h"
#include "BIT_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ICReject */
typedef struct ICReject {
	AlgorithmIdentifier_t	*algorithmIdentifier	/* OPTIONAL */;
	ADSMessage_t	 aDSMessage;
	BIT_STRING_t	 integrityCheck;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ICReject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ICReject;

#ifdef __cplusplus
}
#endif

#endif	/* _ICReject_H_ */
#include "asn_internal.h"
