/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "Intersection.h"

static asn_per_constraints_t asn_PER_type_Intersection_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Intersection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Intersection, choice.intersectionName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AssignedNameShort,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"intersectionName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Intersection, choice.taxiway),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Taxiway,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"taxiway"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Intersection, choice.runway),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Runway,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"runway"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Intersection_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* intersectionName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* taxiway */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* runway */
};
static asn_CHOICE_specifics_t asn_SPC_Intersection_specs_1 = {
	sizeof(struct Intersection),
	offsetof(struct Intersection, _asn_ctx),
	offsetof(struct Intersection, present),
	sizeof(((struct Intersection *)0)->present),
	asn_MAP_Intersection_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Intersection = {
	"Intersection",
	"Intersection",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Intersection_constr_1,
	asn_MBR_Intersection_1,
	3,	/* Elements count */
	&asn_SPC_Intersection_specs_1	/* Additional specs */
};

