/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ITPReferenceAircraftDistance_H_
#define	_ITPReferenceAircraftDistance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Distance.h"
#include "LocationQualifier.h"
#include "AircraftIdentification.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ITPReferenceAircraftDistance */
typedef struct ITPReferenceAircraftDistance {
	Distance_t	 distance;
	LocationQualifier_t	 locationQualifier;
	AircraftIdentification_t	 aircraftId;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITPReferenceAircraftDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITPReferenceAircraftDistance;

#ifdef __cplusplus
}
#endif

#endif	/* _ITPReferenceAircraftDistance_H_ */
#include "asn_internal.h"
