/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "LateralType.h"

static asn_TYPE_member_t asn_MBR_LateralType_1[] = {
	{ ATF_POINTER, 10, offsetof(struct LateralType, flyby),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TurnRadiusO,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"flyby"
		},
	{ ATF_POINTER, 9, offsetof(struct LateralType, fixedRadiusTransition),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TurnRadiusO,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fixedRadiusTransition"
		},
	{ ATF_POINTER, 8, offsetof(struct LateralType, offsetStart),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"offsetStart"
		},
	{ ATF_POINTER, 7, offsetof(struct LateralType, offsetReached),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"offsetReached"
		},
	{ ATF_POINTER, 6, offsetof(struct LateralType, returnToParentPathInitiation),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"returnToParentPathInitiation"
		},
	{ ATF_POINTER, 5, offsetof(struct LateralType, offsetEnd),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"offsetEnd"
		},
	{ ATF_POINTER, 4, offsetof(struct LateralType, offset),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"offset"
		},
	{ ATF_POINTER, 3, offsetof(struct LateralType, overfly),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"overfly"
		},
	{ ATF_POINTER, 2, offsetof(struct LateralType, flightPlanWayPoint),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"flightPlanWayPoint"
		},
	{ ATF_POINTER, 1, offsetof(struct LateralType, followedByDisco),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"followedByDisco"
		},
};
static const int asn_MAP_LateralType_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_LateralType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LateralType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* flyby */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* fixedRadiusTransition */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* offsetStart */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* offsetReached */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* returnToParentPathInitiation */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* offsetEnd */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* offset */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* overfly */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* flightPlanWayPoint */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* followedByDisco */
};
static asn_SEQUENCE_specifics_t asn_SPC_LateralType_specs_1 = {
	sizeof(struct LateralType),
	offsetof(struct LateralType, _asn_ctx),
	asn_MAP_LateralType_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_LateralType_oms_1,	/* Optional members */
	10, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LateralType = {
	"LateralType",
	"LateralType",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LateralType_tags_1,
	sizeof(asn_DEF_LateralType_tags_1)
		/sizeof(asn_DEF_LateralType_tags_1[0]), /* 1 */
	asn_DEF_LateralType_tags_1,	/* Same as above */
	sizeof(asn_DEF_LateralType_tags_1)
		/sizeof(asn_DEF_LateralType_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LateralType_1,
	10,	/* Elements count */
	&asn_SPC_LateralType_specs_1	/* Additional specs */
};

