/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LateralType_H_
#define	_LateralType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TurnRadiusO;

/* LateralType */
typedef struct LateralType {
	struct TurnRadiusO	*flyby	/* OPTIONAL */;
	struct TurnRadiusO	*fixedRadiusTransition	/* OPTIONAL */;
	NULL_t	*offsetStart	/* OPTIONAL */;
	NULL_t	*offsetReached	/* OPTIONAL */;
	NULL_t	*returnToParentPathInitiation	/* OPTIONAL */;
	NULL_t	*offsetEnd	/* OPTIONAL */;
	NULL_t	*offset	/* OPTIONAL */;
	NULL_t	*overfly	/* OPTIONAL */;
	NULL_t	*flightPlanWayPoint	/* OPTIONAL */;
	NULL_t	*followedByDisco	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LateralType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LateralType;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TurnRadiusO.h"

#endif	/* _LateralType_H_ */
#include "asn_internal.h"
