/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LatitudeLongitude_H_
#define	_LatitudeLongitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Latitude;
struct Longitude;

/* LatitudeLongitude */
typedef struct LatitudeLongitude {
	struct Latitude	*latitude	/* OPTIONAL */;
	struct Longitude	*longitude	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LatitudeLongitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LatitudeLongitude;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Latitude.h"
#include "Longitude.h"

#endif	/* _LatitudeLongitude_H_ */
#include "asn_internal.h"
