/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LeaveInstruction_H_
#define	_LeaveInstruction_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LeaveInstructionDescending.h"
#include "LeaveInstructionClimbing.h"
#include "LevelS.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LeaveInstruction_PR {
	LeaveInstruction_PR_NOTHING,	/* No components present */
	LeaveInstruction_PR_descending,
	LeaveInstruction_PR_climbing,
	LeaveInstruction_PR_atLevel
} LeaveInstruction_PR;

/* LeaveInstruction */
typedef struct LeaveInstruction {
	LeaveInstruction_PR present;
	union LeaveInstruction_u {
		LeaveInstructionDescending_t	 descending;
		LeaveInstructionClimbing_t	 climbing;
		LevelS_t	 atLevel;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LeaveInstruction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LeaveInstruction;

#ifdef __cplusplus
}
#endif

#endif	/* _LeaveInstruction_H_ */
#include "asn_internal.h"
