/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LeaveInstructionO_H_
#define	_LeaveInstructionO_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LeaveInstructionNone.h"
#include "LeaveInstruction.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LeaveInstructionO_PR {
	LeaveInstructionO_PR_NOTHING,	/* No components present */
	LeaveInstructionO_PR_none,
	LeaveInstructionO_PR_value
} LeaveInstructionO_PR;

/* LeaveInstructionO */
typedef struct LeaveInstructionO {
	LeaveInstructionO_PR present;
	union LeaveInstructionO_u {
		LeaveInstructionNone_t	 none;
		LeaveInstruction_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LeaveInstructionO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LeaveInstructionO;

#ifdef __cplusplus
}
#endif

#endif	/* _LeaveInstructionO_H_ */
#include "asn_internal.h"
