/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_LegDistanceMetric_H_
#define	_LegDistanceMetric_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LegDistanceMetric */
typedef long	 LegDistanceMetric_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LegDistanceMetric;
asn_struct_free_f LegDistanceMetric_free;
asn_struct_print_f LegDistanceMetric_print;
asn_constr_check_f LegDistanceMetric_constraint;
ber_type_decoder_f LegDistanceMetric_decode_ber;
der_type_encoder_f LegDistanceMetric_encode_der;
xer_type_decoder_f LegDistanceMetric_decode_xer;
xer_type_encoder_f LegDistanceMetric_encode_xer;
per_type_decoder_f LegDistanceMetric_decode_uper;
per_type_encoder_f LegDistanceMetric_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LegDistanceMetric_H_ */
#include <asn_internal.h>
