/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LegDistanceEnglish_H_
#define	_LegDistanceEnglish_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LegDistanceEnglish */
typedef long	 LegDistanceEnglish_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LegDistanceEnglish;
asn_struct_free_f LegDistanceEnglish_free;
asn_struct_print_f LegDistanceEnglish_print;
asn_constr_check_f LegDistanceEnglish_constraint;
ber_type_decoder_f LegDistanceEnglish_decode_ber;
der_type_encoder_f LegDistanceEnglish_encode_der;
xer_type_decoder_f LegDistanceEnglish_decode_xer;
xer_type_encoder_f LegDistanceEnglish_encode_xer;
per_type_decoder_f LegDistanceEnglish_decode_uper;
per_type_encoder_f LegDistanceEnglish_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LegDistanceEnglish_H_ */
#include "asn_internal.h"
