/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LegTimeR_H_
#define	_LegTimeR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LegTimeR */
typedef long	 LegTimeR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LegTimeR;
asn_struct_free_f LegTimeR_free;
asn_struct_print_f LegTimeR_print;
asn_constr_check_f LegTimeR_constraint;
ber_type_decoder_f LegTimeR_decode_ber;
der_type_encoder_f LegTimeR_encode_der;
xer_type_decoder_f LegTimeR_decode_xer;
xer_type_encoder_f LegTimeR_encode_xer;
per_type_decoder_f LegTimeR_decode_uper;
per_type_encoder_f LegTimeR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LegTimeR_H_ */
#include "asn_internal.h"
