/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LevelsOfFlight_H_
#define	_LevelsOfFlight_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Level.h"
#include "ProcedureName.h"
#include "LevelProcedureName.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LevelsOfFlight_PR {
	LevelsOfFlight_PR_NOTHING,	/* No components present */
	LevelsOfFlight_PR_level,
	LevelsOfFlight_PR_procedureName,
	LevelsOfFlight_PR_levelProcedureName
} LevelsOfFlight_PR;

/* LevelsOfFlight */
typedef struct LevelsOfFlight {
	LevelsOfFlight_PR present;
	union LevelsOfFlight_u {
		Level_t	 level;
		ProcedureName_t	 procedureName;
		LevelProcedureName_t	 levelProcedureName;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LevelsOfFlight_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LevelsOfFlight;

#ifdef __cplusplus
}
#endif

#endif	/* _LevelsOfFlight_H_ */
#include "asn_internal.h"
