/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_LevelConstraintQualifier_H_
#define	_LevelConstraintQualifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LevelConstraintQualifier {
	LevelConstraintQualifier_atOrAbove	= 0,
	LevelConstraintQualifier_atOrBelow	= 1,
	LevelConstraintQualifier_at	= 2
} e_LevelConstraintQualifier;

/* LevelConstraintQualifier */
typedef long	 LevelConstraintQualifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LevelConstraintQualifier;
asn_struct_free_f LevelConstraintQualifier_free;
asn_struct_print_f LevelConstraintQualifier_print;
asn_constr_check_f LevelConstraintQualifier_constraint;
ber_type_decoder_f LevelConstraintQualifier_decode_ber;
der_type_encoder_f LevelConstraintQualifier_encode_der;
xer_type_decoder_f LevelConstraintQualifier_decode_xer;
xer_type_encoder_f LevelConstraintQualifier_encode_xer;
per_type_decoder_f LevelConstraintQualifier_decode_uper;
per_type_encoder_f LevelConstraintQualifier_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LevelConstraintQualifier_H_ */
#include "asn_internal.h"
