/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_MachNumberTolerance_H_
#define	_MachNumberTolerance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MachNumberTolerance */
typedef long	 MachNumberTolerance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MachNumberTolerance;
asn_struct_free_f MachNumberTolerance_free;
asn_struct_print_f MachNumberTolerance_print;
asn_constr_check_f MachNumberTolerance_constraint;
ber_type_decoder_f MachNumberTolerance_decode_ber;
der_type_encoder_f MachNumberTolerance_encode_der;
xer_type_decoder_f MachNumberTolerance_decode_xer;
xer_type_encoder_f MachNumberTolerance_encode_xer;
per_type_decoder_f MachNumberTolerance_decode_uper;
per_type_encoder_f MachNumberTolerance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MachNumberTolerance_H_ */
#include "asn_internal.h"
