/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_MsgIdentificationNumber_H_
#define	_MsgIdentificationNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MsgIdentificationNumber */
typedef long	 MsgIdentificationNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgIdentificationNumber;
asn_struct_free_f MsgIdentificationNumber_free;
asn_struct_print_f MsgIdentificationNumber_print;
asn_constr_check_f MsgIdentificationNumber_constraint;
ber_type_decoder_f MsgIdentificationNumber_decode_ber;
der_type_encoder_f MsgIdentificationNumber_encode_der;
xer_type_decoder_f MsgIdentificationNumber_decode_xer;
xer_type_encoder_f MsgIdentificationNumber_encode_xer;
per_type_decoder_f MsgIdentificationNumber_decode_uper;
per_type_encoder_f MsgIdentificationNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgIdentificationNumber_H_ */
#include "asn_internal.h"
