/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_MsgReferenceNumber_H_
#define	_MsgReferenceNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MsgReferenceNumber */
typedef long	 MsgReferenceNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgReferenceNumber;
asn_struct_free_f MsgReferenceNumber_free;
asn_struct_print_f MsgReferenceNumber_print;
asn_constr_check_f MsgReferenceNumber_constraint;
ber_type_decoder_f MsgReferenceNumber_decode_ber;
der_type_encoder_f MsgReferenceNumber_encode_der;
xer_type_decoder_f MsgReferenceNumber_decode_xer;
xer_type_encoder_f MsgReferenceNumber_encode_xer;
per_type_decoder_f MsgReferenceNumber_decode_uper;
per_type_encoder_f MsgReferenceNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgReferenceNumber_H_ */
#include "asn_internal.h"
