/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_OCLRequestNone_H_
#define	_OCLRequestNone_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OCLRequestNone */
typedef NULL_t	 OCLRequestNone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OCLRequestNone;
asn_struct_free_f OCLRequestNone_free;
asn_struct_print_f OCLRequestNone_print;
asn_constr_check_f OCLRequestNone_constraint;
ber_type_decoder_f OCLRequestNone_decode_ber;
der_type_encoder_f OCLRequestNone_encode_der;
xer_type_decoder_f OCLRequestNone_decode_xer;
xer_type_encoder_f OCLRequestNone_encode_xer;
per_type_decoder_f OCLRequestNone_decode_uper;
per_type_encoder_f OCLRequestNone_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _OCLRequestNone_H_ */
#include "asn_internal.h"
