/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_PositionSpeedSpeed_H_
#define	_PositionSpeedSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Position.h"
#include "SpeedSpeed.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PositionSpeedSpeed */
typedef struct PositionSpeedSpeed {
	Position_t	 position;
	SpeedSpeed_t	 speeds;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionSpeedSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionSpeedSpeed;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionSpeedSpeed_H_ */
#include "asn_internal.h"
