/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_PositionSpeed_H_
#define	_PositionSpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "Speed.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionSpeed */
typedef struct PositionSpeed {
	Position_t	 position;
	Speed_t	 speed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionSpeed;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionSpeed_H_ */
#include <asn_internal.h>
