/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_PositionGroundair_H_
#define	_PositionGroundair_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PositionR.h"
#include "GroundLocation.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PositionGroundair_PR {
	PositionGroundair_PR_NOTHING,	/* No components present */
	PositionGroundair_PR_airPosition,
	PositionGroundair_PR_groundLocation
} PositionGroundair_PR;

/* PositionGroundair */
typedef struct PositionGroundair {
	PositionGroundair_PR present;
	union PositionGroundair_u {
		PositionR_t	 airPosition;
		GroundLocation_t	 groundLocation;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionGroundair_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionGroundair;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionGroundair_H_ */
#include "asn_internal.h"
