/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_PositionGAUnitNameRFrequencyO_H_
#define	_PositionGAUnitNameRFrequencyO_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PositionGroundair.h"
#include "UnitNameR.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FrequencyR;

/* PositionGAUnitNameRFrequencyO */
typedef struct PositionGAUnitNameRFrequencyO {
	PositionGroundair_t	 positionGroundair;
	UnitNameR_t	 unitName;
	struct FrequencyR	*frequency	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionGAUnitNameRFrequencyO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionGAUnitNameRFrequencyO;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FrequencyR.h"

#endif	/* _PositionGAUnitNameRFrequencyO_H_ */
#include "asn_internal.h"
