/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMADSCAPDUVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_pmadsc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ProviderAbortReason_H_
#define	_ProviderAbortReason_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProviderAbortReason {
	ProviderAbortReason_communications_service_failure	= 0,
	ProviderAbortReason_unrecoverable_system_error	= 1,
	ProviderAbortReason_invalid_PDU	= 2,
	ProviderAbortReason_sequence_error	= 3,
	ProviderAbortReason_timer_expiry	= 4,
	ProviderAbortReason_cannot_establish_contact	= 5,
	ProviderAbortReason_undefined_error	= 6,
	ProviderAbortReason_dialogue_end_not_accepted	= 7,
	ProviderAbortReason_unexpected_PDU	= 8,
	ProviderAbortReason_decoding_error	= 9,
	ProviderAbortReason_invalid_qos_parameter	= 10
	/*
	 * Enumeration is extensible
	 */
} e_ProviderAbortReason;

/* ProviderAbortReason */
typedef long	 ProviderAbortReason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProviderAbortReason;
asn_struct_free_f ProviderAbortReason_free;
asn_struct_print_f ProviderAbortReason_print;
asn_constr_check_f ProviderAbortReason_constraint;
ber_type_decoder_f ProviderAbortReason_decode_ber;
der_type_encoder_f ProviderAbortReason_encode_der;
xer_type_decoder_f ProviderAbortReason_decode_xer;
xer_type_encoder_f ProviderAbortReason_encode_xer;
per_type_decoder_f ProviderAbortReason_decode_uper;
per_type_encoder_f ProviderAbortReason_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProviderAbortReason_H_ */
#include "asn_internal.h"
