/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_PushbackPositionO_H_
#define	_PushbackPositionO_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "PushbackPosition.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PushbackPositionO_PR {
	PushbackPositionO_PR_NOTHING,	/* No components present */
	PushbackPositionO_PR_none,
	PushbackPositionO_PR_value
} PushbackPositionO_PR;

/* PushbackPositionO */
typedef struct PushbackPositionO {
	PushbackPositionO_PR present;
	union PushbackPositionO_u {
		NULL_t	 none;
		PushbackPosition_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PushbackPositionO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PushbackPositionO;

#ifdef __cplusplus
}
#endif

#endif	/* _PushbackPositionO_H_ */
#include "asn_internal.h"
