/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_QNHAltitude_H_
#define	_QNHAltitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ADSv2Level.h"
#include "Altimeter.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* QNHAltitude */
typedef struct QNHAltitude {
	ADSv2Level_t	 altitude;
	Altimeter_t	 qNH;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QNHAltitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QNHAltitude;

#ifdef __cplusplus
}
#endif

#endif	/* _QNHAltitude_H_ */
#include "asn_internal.h"
