/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_Ramp_H_
#define	_Ramp_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "AssignedNameShort.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ramp_PR {
	Ramp_PR_NOTHING,	/* No components present */
	Ramp_PR_noName,
	Ramp_PR_rampName
} Ramp_PR;

/* Ramp */
typedef struct Ramp {
	Ramp_PR present;
	union Ramp_u {
		NULL_t	 noName;
		AssignedNameShort_t	 rampName;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ramp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ramp;

#ifdef __cplusplus
}
#endif

#endif	/* _Ramp_H_ */
#include "asn_internal.h"
