/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "RemainingFuelPersonsOnBoardE.h"

static asn_TYPE_member_t asn_MBR_RemainingFuelPersonsOnBoardE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RemainingFuelPersonsOnBoardE, remainingFuel),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RemainingFuel,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"remainingFuel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemainingFuelPersonsOnBoardE, personsOnBoard),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_PersonsOnBoardEnhanced,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"personsOnBoard"
		},
};
static const ber_tlv_tag_t asn_DEF_RemainingFuelPersonsOnBoardE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RemainingFuelPersonsOnBoardE_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* remainingFuel */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* unknownNumber */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* personsOnBoard */
};
static asn_SEQUENCE_specifics_t asn_SPC_RemainingFuelPersonsOnBoardE_specs_1 = {
	sizeof(struct RemainingFuelPersonsOnBoardE),
	offsetof(struct RemainingFuelPersonsOnBoardE, _asn_ctx),
	asn_MAP_RemainingFuelPersonsOnBoardE_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RemainingFuelPersonsOnBoardE = {
	"RemainingFuelPersonsOnBoardE",
	"RemainingFuelPersonsOnBoardE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RemainingFuelPersonsOnBoardE_tags_1,
	sizeof(asn_DEF_RemainingFuelPersonsOnBoardE_tags_1)
		/sizeof(asn_DEF_RemainingFuelPersonsOnBoardE_tags_1[0]), /* 1 */
	asn_DEF_RemainingFuelPersonsOnBoardE_tags_1,	/* Same as above */
	sizeof(asn_DEF_RemainingFuelPersonsOnBoardE_tags_1)
		/sizeof(asn_DEF_RemainingFuelPersonsOnBoardE_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RemainingFuelPersonsOnBoardE_1,
	2,	/* Elements count */
	&asn_SPC_RemainingFuelPersonsOnBoardE_specs_1	/* Additional specs */
};

