/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ReportingRate_H_
#define	_ReportingRate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportingRate_PR {
	ReportingRate_PR_NOTHING,	/* No components present */
	ReportingRate_PR_reporting_time_seconds_scale,
	ReportingRate_PR_reporting_time_minutes_scale
} ReportingRate_PR;

/* ReportingRate */
typedef struct ReportingRate {
	ReportingRate_PR present;
	union ReportingRate_u {
		long	 reporting_time_seconds_scale;
		long	 reporting_time_minutes_scale;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportingRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportingRate;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportingRate_H_ */
#include "asn_internal.h"
