/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_RevisionReasonSequence_H_
#define	_RevisionReasonSequence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RevisionReason;

/* RevisionReasonSequence */
typedef struct RevisionReasonSequence {
	A_SEQUENCE_OF(struct RevisionReason) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevisionReasonSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevisionReasonSequence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RevisionReason.h"

#endif	/* _RevisionReasonSequence_H_ */
#include "asn_internal.h"
