/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "RouteInformationAdditionalR.h"

static asn_TYPE_member_t asn_MBR_RouteInformationAdditionalR_1[] = {
	{ ATF_POINTER, 4, offsetof(struct RouteInformationAdditionalR, aTWAlongTrackWaypoints),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ATWAlongTrackWaypointRSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aTWAlongTrackWaypoints"
		},
	{ ATF_POINTER, 3, offsetof(struct RouteInformationAdditionalR, holdAtWaypoints),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_HoldatwaypointRSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"holdAtWaypoints"
		},
	{ ATF_POINTER, 2, offsetof(struct RouteInformationAdditionalR, waypointSpeedLevels),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_WaypointSpeedLevelRSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"waypointSpeedLevels"
		},
	{ ATF_POINTER, 1, offsetof(struct RouteInformationAdditionalR, rTARequiredTimeArrivals),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RTAsecRequiredTimeArrivalSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rTARequiredTimeArrivals"
		},
};
static const int asn_MAP_RouteInformationAdditionalR_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_RouteInformationAdditionalR_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RouteInformationAdditionalR_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aTWAlongTrackWaypoints */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* holdAtWaypoints */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* waypointSpeedLevels */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* rTARequiredTimeArrivals */
};
static asn_SEQUENCE_specifics_t asn_SPC_RouteInformationAdditionalR_specs_1 = {
	sizeof(struct RouteInformationAdditionalR),
	offsetof(struct RouteInformationAdditionalR, _asn_ctx),
	asn_MAP_RouteInformationAdditionalR_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RouteInformationAdditionalR_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RouteInformationAdditionalR = {
	"RouteInformationAdditionalR",
	"RouteInformationAdditionalR",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RouteInformationAdditionalR_tags_1,
	sizeof(asn_DEF_RouteInformationAdditionalR_tags_1)
		/sizeof(asn_DEF_RouteInformationAdditionalR_tags_1[0]), /* 1 */
	asn_DEF_RouteInformationAdditionalR_tags_1,	/* Same as above */
	sizeof(asn_DEF_RouteInformationAdditionalR_tags_1)
		/sizeof(asn_DEF_RouteInformationAdditionalR_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RouteInformationAdditionalR_1,
	4,	/* Elements count */
	&asn_SPC_RouteInformationAdditionalR_specs_1	/* Additional specs */
};

