/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "RouteInformationAdditional.h"

static asn_TYPE_member_t asn_MBR_RouteInformationAdditional_1[] = {
	{ ATF_POINTER, 6, offsetof(struct RouteInformationAdditional, aTWAlongTrackWaypoints),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ATWAlongTrackWaypointSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aTWAlongTrackWaypoints"
		},
	{ ATF_POINTER, 5, offsetof(struct RouteInformationAdditional, reportingpoints),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ReportingPoints,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportingpoints"
		},
	{ ATF_POINTER, 4, offsetof(struct RouteInformationAdditional, interceptCourseFroms),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_InterceptCourseFromSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"interceptCourseFroms"
		},
	{ ATF_POINTER, 3, offsetof(struct RouteInformationAdditional, holdAtWaypoints),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_HoldatwaypointSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"holdAtWaypoints"
		},
	{ ATF_POINTER, 2, offsetof(struct RouteInformationAdditional, waypointSpeedLevels),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_WaypointSpeedLevelSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"waypointSpeedLevels"
		},
	{ ATF_POINTER, 1, offsetof(struct RouteInformationAdditional, rTARequiredTimeArrivals),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RTARequiredTimeArrivalSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rTARequiredTimeArrivals"
		},
};
static const int asn_MAP_RouteInformationAdditional_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_RouteInformationAdditional_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RouteInformationAdditional_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aTWAlongTrackWaypoints */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reportingpoints */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* interceptCourseFroms */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* holdAtWaypoints */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* waypointSpeedLevels */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* rTARequiredTimeArrivals */
};
static asn_SEQUENCE_specifics_t asn_SPC_RouteInformationAdditional_specs_1 = {
	sizeof(struct RouteInformationAdditional),
	offsetof(struct RouteInformationAdditional, _asn_ctx),
	asn_MAP_RouteInformationAdditional_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_RouteInformationAdditional_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RouteInformationAdditional = {
	"RouteInformationAdditional",
	"RouteInformationAdditional",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RouteInformationAdditional_tags_1,
	sizeof(asn_DEF_RouteInformationAdditional_tags_1)
		/sizeof(asn_DEF_RouteInformationAdditional_tags_1[0]), /* 1 */
	asn_DEF_RouteInformationAdditional_tags_1,	/* Same as above */
	sizeof(asn_DEF_RouteInformationAdditional_tags_1)
		/sizeof(asn_DEF_RouteInformationAdditional_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RouteInformationAdditional_1,
	6,	/* Elements count */
	&asn_SPC_RouteInformationAdditional_specs_1	/* Additional specs */
};

