/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_RouteClearanceConstrainedData_H_
#define	_RouteClearanceConstrainedData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RouteClearanceSequence;

/* RouteClearanceConstrainedData */
typedef struct RouteClearanceConstrainedData {
	struct RouteClearanceSequence	*routeClearanceData	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RouteClearanceConstrainedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RouteClearanceConstrainedData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RouteClearanceSequence.h"

#endif	/* _RouteClearanceConstrainedData_H_ */
#include "asn_internal.h"
