/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_RunwayOIntersectionDistanceGroundO_H_
#define	_RunwayOIntersectionDistanceGroundO_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Intersection.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Runway;
struct DistanceGround;

/* RunwayOIntersectionDistanceGroundO */
typedef struct RunwayOIntersectionDistanceGroundO {
	struct Runway	*runway	/* OPTIONAL */;
	Intersection_t	 intersection;
	struct DistanceGround	*distanceGround	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RunwayOIntersectionDistanceGroundO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RunwayOIntersectionDistanceGroundO;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Runway.h"
#include "DistanceGround.h"

#endif	/* _RunwayOIntersectionDistanceGroundO_H_ */
#include "asn_internal.h"
