/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_RunwayConfiguration_H_
#define	_RunwayConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RunwayConfiguration {
	RunwayConfiguration_left	= 0,
	RunwayConfiguration_right	= 1,
	RunwayConfiguration_center	= 2,
	RunwayConfiguration_none	= 3
} e_RunwayConfiguration;

/* RunwayConfiguration */
typedef long	 RunwayConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RunwayConfiguration;
asn_struct_free_f RunwayConfiguration_free;
asn_struct_print_f RunwayConfiguration_print;
asn_constr_check_f RunwayConfiguration_constraint;
ber_type_decoder_f RunwayConfiguration_decode_ber;
der_type_encoder_f RunwayConfiguration_encode_der;
xer_type_decoder_f RunwayConfiguration_decode_xer;
xer_type_encoder_f RunwayConfiguration_encode_xer;
per_type_decoder_f RunwayConfiguration_decode_uper;
per_type_encoder_f RunwayConfiguration_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RunwayConfiguration_H_ */
#include "asn_internal.h"
