/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_RunwayO_H_
#define	_RunwayO_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "Runway.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RunwayO_PR {
	RunwayO_PR_NOTHING,	/* No components present */
	RunwayO_PR_none,
	RunwayO_PR_value
} RunwayO_PR;

/* RunwayO */
typedef struct RunwayO {
	RunwayO_PR present;
	union RunwayO_u {
		NULL_t	 none;
		Runway_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RunwayO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RunwayO;

#ifdef __cplusplus
}
#endif

#endif	/* _RunwayO_H_ */
#include "asn_internal.h"
