/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_SARSpecification_H_
#define	_SARSpecification_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Time.h"
#include "LatitudeLongitudeR.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SARSpecification */
typedef struct SARSpecification {
	Time_t	 timeOfObservation;
	LatitudeLongitudeR_t	 latlong;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SARSpecification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SARSpecification;

#ifdef __cplusplus
}
#endif

#endif	/* _SARSpecification_H_ */
#include "asn_internal.h"
