/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_SpeedTypeR_H_
#define	_SpeedTypeR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpeedTypeR {
	SpeedTypeR_indicated	= 0,
	SpeedTypeR_trueSpeed	= 1,
	SpeedTypeR_ground	= 2,
	SpeedTypeR_mach	= 3,
	SpeedTypeR_approach	= 4,
	SpeedTypeR_cruise	= 5,
	SpeedTypeR_present	= 6
	/*
	 * Enumeration is extensible
	 */
} e_SpeedTypeR;

/* SpeedTypeR */
typedef long	 SpeedTypeR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedTypeR;
asn_struct_free_f SpeedTypeR_free;
asn_struct_print_f SpeedTypeR_print;
asn_constr_check_f SpeedTypeR_constraint;
ber_type_decoder_f SpeedTypeR_decode_ber;
der_type_encoder_f SpeedTypeR_encode_der;
xer_type_decoder_f SpeedTypeR_decode_xer;
xer_type_encoder_f SpeedTypeR_encode_xer;
per_type_decoder_f SpeedTypeR_decode_uper;
per_type_encoder_f SpeedTypeR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedTypeR_H_ */
#include "asn_internal.h"
