/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_SpeedIndicated_H_
#define	_SpeedIndicated_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SpeedIndicated */
typedef long	 SpeedIndicated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedIndicated;
asn_struct_free_f SpeedIndicated_free;
asn_struct_print_f SpeedIndicated_print;
asn_constr_check_f SpeedIndicated_constraint;
ber_type_decoder_f SpeedIndicated_decode_ber;
der_type_encoder_f SpeedIndicated_encode_der;
xer_type_decoder_f SpeedIndicated_decode_xer;
xer_type_encoder_f SpeedIndicated_encode_xer;
per_type_decoder_f SpeedIndicated_decode_uper;
per_type_encoder_f SpeedIndicated_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedIndicated_H_ */
#include "asn_internal.h"
