/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_SpeedScheduleProfile_H_
#define	_SpeedScheduleProfile_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GrossMass.h"
#include "SpeedScheduleBlock.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedScheduleBlock;
struct SpeedScheduleSingle;

/* SpeedScheduleProfile */
typedef struct SpeedScheduleProfile {
	GrossMass_t	*predicted_gross_mass_at_tod	/* OPTIONAL */;
	struct SpeedScheduleBlock	*climbSpeed	/* OPTIONAL */;
	struct SpeedScheduleSingle	*initialCruiseSpeedAtTOC	/* OPTIONAL */;
	struct SpeedScheduleSingle	*finalCruiseSpeedAtTOD	/* OPTIONAL */;
	SpeedScheduleBlock_t	 descentSpeed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpeedScheduleProfile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedScheduleProfile;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SpeedScheduleBlock.h"
#include "SpeedScheduleSingle.h"

#endif	/* _SpeedScheduleProfile_H_ */
#include "asn_internal.h"
