/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_SpeedIASMach_H_
#define	_SpeedIASMach_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SpeedMach.h"
#include "Ias.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpeedIASMach_PR {
	SpeedIASMach_PR_NOTHING,	/* No components present */
	SpeedIASMach_PR_mach,
	SpeedIASMach_PR_ias
} SpeedIASMach_PR;

/* SpeedIASMach */
typedef struct SpeedIASMach {
	SpeedIASMach_PR present;
	union SpeedIASMach_u {
		SpeedMach_t	 mach;
		Ias_t	 ias;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpeedIASMach_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedIASMach;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedIASMach_H_ */
#include "asn_internal.h"
