/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_SpeedTypeSpeedTypeSpeedTypeSpeed_H_
#define	_SpeedTypeSpeedTypeSpeedTypeSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SpeedTypeSpeedTypeSpeedType.h"
#include "Speed.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SpeedTypeSpeedTypeSpeedTypeSpeed */
typedef struct SpeedTypeSpeedTypeSpeedTypeSpeed {
	SpeedTypeSpeedTypeSpeedType_t	 speedTypes;
	Speed_t	 speed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpeedTypeSpeedTypeSpeedTypeSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedTypeSpeedTypeSpeedTypeSpeed;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedTypeSpeedTypeSpeedTypeSpeed_H_ */
#include "asn_internal.h"
