/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_TimeTolerance_H_
#define	_TimeTolerance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeTolerance {
	TimeTolerance_at	= 0,
	TimeTolerance_atorafter	= 1,
	TimeTolerance_atorbefore	= 2
} e_TimeTolerance;

/* TimeTolerance */
typedef long	 TimeTolerance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeTolerance;
asn_struct_free_f TimeTolerance_free;
asn_struct_print_f TimeTolerance_print;
asn_constr_check_f TimeTolerance_constraint;
ber_type_decoder_f TimeTolerance_decode_ber;
der_type_encoder_f TimeTolerance_encode_der;
xer_type_decoder_f TimeTolerance_decode_xer;
xer_type_encoder_f TimeTolerance_encode_xer;
per_type_decoder_f TimeTolerance_decode_uper;
per_type_encoder_f TimeTolerance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeTolerance_H_ */
#include "asn_internal.h"
