/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "TimeDeparture.h"

static asn_TYPE_member_t asn_MBR_TimeDeparture_1[] = {
	{ ATF_POINTER, 4, offsetof(struct TimeDeparture, timeDepartureAllocated),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeDepartureAllocated"
		},
	{ ATF_POINTER, 3, offsetof(struct TimeDeparture, timeDepartureControlled),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ControlledTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeDepartureControlled"
		},
	{ ATF_POINTER, 2, offsetof(struct TimeDeparture, timeDepartureClearanceExpected),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeDepartureClearanceExpected"
		},
	{ ATF_POINTER, 1, offsetof(struct TimeDeparture, departureMinimumInterval),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DepartureMinimumInterval,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"departureMinimumInterval"
		},
};
static const int asn_MAP_TimeDeparture_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_TimeDeparture_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TimeDeparture_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* timeDepartureAllocated */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* timeDepartureControlled */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* timeDepartureClearanceExpected */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* departureMinimumInterval */
};
static asn_SEQUENCE_specifics_t asn_SPC_TimeDeparture_specs_1 = {
	sizeof(struct TimeDeparture),
	offsetof(struct TimeDeparture, _asn_ctx),
	asn_MAP_TimeDeparture_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_TimeDeparture_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TimeDeparture = {
	"TimeDeparture",
	"TimeDeparture",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TimeDeparture_tags_1,
	sizeof(asn_DEF_TimeDeparture_tags_1)
		/sizeof(asn_DEF_TimeDeparture_tags_1[0]), /* 1 */
	asn_DEF_TimeDeparture_tags_1,	/* Same as above */
	sizeof(asn_DEF_TimeDeparture_tags_1)
		/sizeof(asn_DEF_TimeDeparture_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TimeDeparture_1,
	4,	/* Elements count */
	&asn_SPC_TimeDeparture_specs_1	/* Additional specs */
};

