/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_TimePositionR_H_
#define	_TimePositionR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Time.h"
#include "PositionR.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TimePositionR */
typedef struct TimePositionR {
	Time_t	 time;
	PositionR_t	 position;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimePositionR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimePositionR;

#ifdef __cplusplus
}
#endif

#endif	/* _TimePositionR_H_ */
#include "asn_internal.h"
