/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "Timesec.h"

static asn_TYPE_member_t asn_MBR_Timesec_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Timesec, hours),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_TimeHours,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"hours"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Timesec, minutes),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_TimeMinutes,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"minutes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Timesec, seconds),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_TimeSeconds,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"seconds"
		},
};
static const ber_tlv_tag_t asn_DEF_Timesec_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Timesec_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* hours */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* minutes */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 } /* seconds */
};
static asn_SEQUENCE_specifics_t asn_SPC_Timesec_specs_1 = {
	sizeof(struct Timesec),
	offsetof(struct Timesec, _asn_ctx),
	asn_MAP_Timesec_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Timesec = {
	"Timesec",
	"Timesec",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Timesec_tags_1,
	sizeof(asn_DEF_Timesec_tags_1)
		/sizeof(asn_DEF_Timesec_tags_1[0]), /* 1 */
	asn_DEF_Timesec_tags_1,	/* Same as above */
	sizeof(asn_DEF_Timesec_tags_1)
		/sizeof(asn_DEF_Timesec_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Timesec_1,
	3,	/* Elements count */
	&asn_SPC_Timesec_specs_1	/* Additional specs */
};

