/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_ToFromPosition_H_
#define	_ToFromPosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ToFrom.h"
#include "Position.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ToFromPosition */
typedef struct ToFromPosition {
	ToFrom_t	 toFrom;
	Position_t	 position;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ToFromPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ToFromPosition;

#ifdef __cplusplus
}
#endif

#endif	/* _ToFromPosition_H_ */
#include "asn_internal.h"
