/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_TrafficType_H_
#define	_TrafficType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TrafficType {
	TrafficType_noneSpecified	= 0,
	TrafficType_oppositeDirection	= 1,
	TrafficType_sameDirection	= 2,
	TrafficType_converging	= 3,
	TrafficType_crossing	= 4,
	TrafficType_diverging	= 5
	/*
	 * Enumeration is extensible
	 */
} e_TrafficType;

/* TrafficType */
typedef long	 TrafficType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrafficType;
asn_struct_free_f TrafficType_free;
asn_struct_print_f TrafficType_print;
asn_constr_check_f TrafficType_constraint;
ber_type_decoder_f TrafficType_decode_ber;
der_type_encoder_f TrafficType_encode_der;
xer_type_decoder_f TrafficType_decode_xer;
xer_type_encoder_f TrafficType_encode_xer;
per_type_decoder_f TrafficType_decode_uper;
per_type_encoder_f TrafficType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TrafficType_H_ */
#include "asn_internal.h"
