/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_TransferConstraintsUnitNameR_H_
#define	_TransferConstraintsUnitNameR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransferConstraints.h"
#include "UnitNameR.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TransferConstraintsUnitNameR */
typedef struct TransferConstraintsUnitNameR {
	TransferConstraints_t	 constraints;
	UnitNameR_t	 unitName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransferConstraintsUnitNameR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransferConstraintsUnitNameR;

#ifdef __cplusplus
}
#endif

#endif	/* _TransferConstraintsUnitNameR_H_ */
#include "asn_internal.h"
