/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_TurbulenceEDRAverage_H_
#define	_TurbulenceEDRAverage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TurbulenceEDRValue.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TurbulenceEDRAverage */
typedef TurbulenceEDRValue_t	 TurbulenceEDRAverage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TurbulenceEDRAverage;
asn_struct_free_f TurbulenceEDRAverage_free;
asn_struct_print_f TurbulenceEDRAverage_print;
asn_constr_check_f TurbulenceEDRAverage_constraint;
ber_type_decoder_f TurbulenceEDRAverage_decode_ber;
der_type_encoder_f TurbulenceEDRAverage_encode_der;
xer_type_decoder_f TurbulenceEDRAverage_decode_xer;
xer_type_encoder_f TurbulenceEDRAverage_encode_xer;
per_type_decoder_f TurbulenceEDRAverage_decode_uper;
per_type_encoder_f TurbulenceEDRAverage_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TurbulenceEDRAverage_H_ */
#include "asn_internal.h"
