/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "TurbulenceDeviation.h"

static int asn_DFL_2_set_15(int set_value, void **sptr) {
	TurbulenceObservationWindow_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 15 */
		*st = 15;
		return 0;
	} else {
		/* Test default value 15 */
		return (*st == 15);
	}
}
static int asn_DFL_3_set_40(int set_value, void **sptr) {
	TurbulencePeakThreshold_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 40 */
		*st = 40;
		return 0;
	} else {
		/* Test default value 40 */
		return (*st == 40);
	}
}
static asn_TYPE_member_t asn_MBR_TurbulenceDeviation_1[] = {
	{ ATF_POINTER, 2, offsetof(struct TurbulenceDeviation, observation_window),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TurbulenceObservationWindow,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		asn_DFL_2_set_15,	/* DEFAULT 15 */
		"observation-window"
		},
	{ ATF_POINTER, 1, offsetof(struct TurbulenceDeviation, peak_threshold),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TurbulencePeakThreshold,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		asn_DFL_3_set_40,	/* DEFAULT 40 */
		"peak-threshold"
		},
};
static const int asn_MAP_TurbulenceDeviation_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_TurbulenceDeviation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TurbulenceDeviation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* observation-window */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* peak-threshold */
};
static asn_SEQUENCE_specifics_t asn_SPC_TurbulenceDeviation_specs_1 = {
	sizeof(struct TurbulenceDeviation),
	offsetof(struct TurbulenceDeviation, _asn_ctx),
	asn_MAP_TurbulenceDeviation_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_TurbulenceDeviation_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TurbulenceDeviation = {
	"TurbulenceDeviation",
	"TurbulenceDeviation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TurbulenceDeviation_tags_1,
	sizeof(asn_DEF_TurbulenceDeviation_tags_1)
		/sizeof(asn_DEF_TurbulenceDeviation_tags_1[0]), /* 1 */
	asn_DEF_TurbulenceDeviation_tags_1,	/* Same as above */
	sizeof(asn_DEF_TurbulenceDeviation_tags_1)
		/sizeof(asn_DEF_TurbulenceDeviation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TurbulenceDeviation_1,
	2,	/* Elements count */
	&asn_SPC_TurbulenceDeviation_specs_1	/* Additional specs */
};

