/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CMMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_VersionNumber_H_
#define	_VersionNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VersionNumber */
typedef long	 VersionNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VersionNumber;
asn_struct_free_f VersionNumber_free;
asn_struct_print_f VersionNumber_print;
asn_constr_check_f VersionNumber_constraint;
ber_type_decoder_f VersionNumber_decode_ber;
der_type_encoder_f VersionNumber_encode_der;
xer_type_decoder_f VersionNumber_decode_xer;
xer_type_encoder_f VersionNumber_encode_xer;
per_type_decoder_f VersionNumber_decode_uper;
per_type_encoder_f VersionNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VersionNumber_H_ */
#include "asn_internal.h"
