/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_VerticalRateEnglish_H_
#define	_VerticalRateEnglish_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VerticalRateEnglish */
typedef long	 VerticalRateEnglish_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerticalRateEnglish;
asn_struct_free_f VerticalRateEnglish_free;
asn_struct_print_f VerticalRateEnglish_print;
asn_constr_check_f VerticalRateEnglish_constraint;
ber_type_decoder_f VerticalRateEnglish_decode_ber;
der_type_encoder_f VerticalRateEnglish_encode_der;
xer_type_decoder_f VerticalRateEnglish_decode_xer;
xer_type_encoder_f VerticalRateEnglish_encode_xer;
per_type_decoder_f VerticalRateEnglish_decode_uper;
per_type_encoder_f VerticalRateEnglish_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VerticalRateEnglish_H_ */
#include <asn_internal.h>
