/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b1_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_VerticalRate_H_
#define	_VerticalRate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VerticalRateEnglish.h"
#include "VerticalRateMetric.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VerticalRate_PR {
	VerticalRate_PR_NOTHING,	/* No components present */
	VerticalRate_PR_verticalRateEnglish,
	VerticalRate_PR_verticalRateMetric
} VerticalRate_PR;

/* VerticalRate */
typedef struct VerticalRate {
	VerticalRate_PR present;
	union VerticalRate_u {
		VerticalRateEnglish_t	 verticalRateEnglish;
		VerticalRateMetric_t	 verticalRateMetric;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerticalRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerticalRate;

#ifdef __cplusplus
}
#endif

#endif	/* _VerticalRate_H_ */
#include "asn_internal.h"
