/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_WaypointSpeedLevelRSequence_H_
#define	_WaypointSpeedLevelRSequence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WaypointSpeedLevelR;

/* WaypointSpeedLevelRSequence */
typedef struct WaypointSpeedLevelRSequence {
	A_SEQUENCE_OF(struct WaypointSpeedLevelR) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaypointSpeedLevelRSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaypointSpeedLevelRSequence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WaypointSpeedLevelR.h"

#endif	/* _WaypointSpeedLevelRSequence_H_ */
#include "asn_internal.h"
