/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ADSMessageSetVersion2"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_adsc_v2.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_Waypoint_H_
#define	_Waypoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "WaypointName.h"
#include "ADSv2LatitudeLongitude.h"
#include "VerticalType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Waypoint */
typedef struct Waypoint {
	WaypointName_t	*name	/* OPTIONAL */;
	ADSv2LatitudeLongitude_t	 latitudeLongitude;
	VerticalType_t	*vertical_type	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Waypoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Waypoint;

#ifdef __cplusplus
}
#endif

#endif	/* _Waypoint_H_ */
#include "asn_internal.h"
