/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPDLCMessageSetVersion2BCVersion1"
 * 	found in "../../../dumpvdl2.asn1/atn-b2_cpdlc-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_WaypointLevelConstraint_H_
#define	_WaypointLevelConstraint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BlockLevel.h"
#include "ATWLevelS.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WaypointLevelConstraint_PR {
	WaypointLevelConstraint_PR_NOTHING,	/* No components present */
	WaypointLevelConstraint_PR_blockLevel,
	WaypointLevelConstraint_PR_toleranceLevel
} WaypointLevelConstraint_PR;

/* WaypointLevelConstraint */
typedef struct WaypointLevelConstraint {
	WaypointLevelConstraint_PR present;
	union WaypointLevelConstraint_u {
		BlockLevel_t	 blockLevel;
		ATWLevelS_t	 toleranceLevel;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaypointLevelConstraint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaypointLevelConstraint;

#ifdef __cplusplus
}
#endif

#endif	/* _WaypointLevelConstraint_H_ */
#include "asn_internal.h"
