/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_WindDirection_H_
#define	_WindDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WindDirection */
typedef long	 WindDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WindDirection;
asn_struct_free_f WindDirection_free;
asn_struct_print_f WindDirection_print;
asn_constr_check_f WindDirection_constraint;
ber_type_decoder_f WindDirection_decode_ber;
der_type_encoder_f WindDirection_encode_der;
xer_type_decoder_f WindDirection_decode_xer;
xer_type_encoder_f WindDirection_encode_xer;
per_type_decoder_f WindDirection_decode_uper;
per_type_encoder_f WindDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WindDirection_H_ */
#include "asn_internal.h"
