/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_WindSpeed_H_
#define	_WindSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "WindSpeedEnglish.h"
#include "WindSpeedMetric.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WindSpeed_PR {
	WindSpeed_PR_NOTHING,	/* No components present */
	WindSpeed_PR_windSpeedEnglish,
	WindSpeed_PR_windSpeedMetric
} WindSpeed_PR;

/* WindSpeed */
typedef struct WindSpeed {
	WindSpeed_PR present;
	union WindSpeed_u {
		WindSpeedEnglish_t	 windSpeedEnglish;
		WindSpeedMetric_t	 windSpeedMetric;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WindSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WindSpeed;

#ifdef __cplusplus
}
#endif

#endif	/* _WindSpeed_H_ */
#include "asn_internal.h"
