/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CMMessageSetVersion1"
 * 	found in "atn-cm.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_CMLogonResponse_H_
#define	_CMLogonResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AEQualifierVersionAddress;
struct AEQualifierVersion;

/* CMLogonResponse */
typedef struct CMLogonResponse {
	struct CMLogonResponse__airInitiatedApplications {
		A_SEQUENCE_OF(struct AEQualifierVersionAddress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *airInitiatedApplications;
	struct CMLogonResponse__groundOnlyInitiatedApplications {
		A_SEQUENCE_OF(struct AEQualifierVersion) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *groundOnlyInitiatedApplications;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CMLogonResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMLogonResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AEQualifierVersionAddress.h"
#include "AEQualifierVersion.h"

#endif	/* _CMLogonResponse_H_ */
#include <asn_internal.h>
