/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_DistanceSpecifiedNm_H_
#define	_DistanceSpecifiedNm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DistanceSpecifiedNm */
typedef long	 DistanceSpecifiedNm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DistanceSpecifiedNm;
asn_struct_free_f DistanceSpecifiedNm_free;
asn_struct_print_f DistanceSpecifiedNm_print;
asn_constr_check_f DistanceSpecifiedNm_constraint;
ber_type_decoder_f DistanceSpecifiedNm_decode_ber;
der_type_encoder_f DistanceSpecifiedNm_encode_der;
xer_type_decoder_f DistanceSpecifiedNm_decode_xer;
xer_type_encoder_f DistanceSpecifiedNm_encode_xer;
per_type_decoder_f DistanceSpecifiedNm_decode_uper;
per_type_encoder_f DistanceSpecifiedNm_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DistanceSpecifiedNm_H_ */
#include <asn_internal.h>
