/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_FANSPositionTimeTime_H_
#define	_FANSPositionTimeTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FANSPosition.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSTime;

/* FANSPositionTimeTime */
typedef struct FANSPositionTimeTime {
	FANSPosition_t	 position;
	struct FANSPositionTimeTime__time_seqOf {
		A_SEQUENCE_OF(struct FANSTime) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} time_seqOf;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSPositionTimeTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPositionTimeTime;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSTime.h"

#endif	/* _FANSPositionTimeTime_H_ */
#include <asn_internal.h>
