/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "FANSTrackDetail.h"

static int
memb_latitudeLongitude_seqOf_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 128)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_latitudeLongitude_seqOf_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 7,  7,  1,  128 }	/* (SIZE(1..128)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_latitudeLongitude_seqOf_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 7,  7,  1,  128 }	/* (SIZE(1..128)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_latitudeLongitude_seqOf_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FANSLatitudeLongitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_latitudeLongitude_seqOf_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_latitudeLongitude_seqOf_specs_3 = {
	sizeof(struct FANSTrackDetail__latitudeLongitude_seqOf),
	offsetof(struct FANSTrackDetail__latitudeLongitude_seqOf, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_latitudeLongitude_seqOf_3 = {
	"latitudeLongitude-seqOf",
	"latitudeLongitude-seqOf",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_latitudeLongitude_seqOf_tags_3,
	sizeof(asn_DEF_latitudeLongitude_seqOf_tags_3)
		/sizeof(asn_DEF_latitudeLongitude_seqOf_tags_3[0]), /* 1 */
	asn_DEF_latitudeLongitude_seqOf_tags_3,	/* Same as above */
	sizeof(asn_DEF_latitudeLongitude_seqOf_tags_3)
		/sizeof(asn_DEF_latitudeLongitude_seqOf_tags_3[0]), /* 1 */
	&asn_PER_type_latitudeLongitude_seqOf_constr_3,
	asn_MBR_latitudeLongitude_seqOf_3,
	1,	/* Single element */
	&asn_SPC_latitudeLongitude_seqOf_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_FANSTrackDetail_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTrackDetail, trackName),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_FANSTrackName,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"trackName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTrackDetail, latitudeLongitude_seqOf),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_latitudeLongitude_seqOf_3,
		memb_latitudeLongitude_seqOf_constraint_1,
		&asn_PER_memb_latitudeLongitude_seqOf_constr_3,
		0,
		"latitudeLongitude-seqOf"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSTrackDetail_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSTrackDetail_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* latitudeLongitude-seqOf */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* trackName */
};
static asn_SEQUENCE_specifics_t asn_SPC_FANSTrackDetail_specs_1 = {
	sizeof(struct FANSTrackDetail),
	offsetof(struct FANSTrackDetail, _asn_ctx),
	asn_MAP_FANSTrackDetail_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FANSTrackDetail = {
	"FANSTrackDetail",
	"FANSTrackDetail",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_FANSTrackDetail_tags_1,
	sizeof(asn_DEF_FANSTrackDetail_tags_1)
		/sizeof(asn_DEF_FANSTrackDetail_tags_1[0]), /* 1 */
	asn_DEF_FANSTrackDetail_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSTrackDetail_tags_1)
		/sizeof(asn_DEF_FANSTrackDetail_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_FANSTrackDetail_1,
	2,	/* Elements count */
	&asn_SPC_FANSTrackDetail_specs_1	/* Additional specs */
};

