/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PMCPDLCMessageSetVersion1"
 * 	found in "atn-cpdlc.asn1"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_RouteInformationSequence_H_
#define	_RouteInformationSequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RouteInformation;

/* RouteInformationSequence */
typedef struct RouteInformationSequence {
	A_SEQUENCE_OF(struct RouteInformation) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RouteInformationSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RouteInformationSequence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RouteInformation.h"

#endif	/* _RouteInformationSequence_H_ */
#include <asn_internal.h>
